import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {accessGate,passwordHash} from '../server/access.mjs';
import worker from '../dist/server/index.js';
const origin='https://game.example';
async function setup(){const sql=new DatabaseSync(':memory:');for(const name of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')))sql.exec(fs.readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));const salt='12'.repeat(16);return{ACCESS_PASSWORD_HASH:salt+':'+await passwordHash('test-entry',salt),ACCESS_SESSION_KEY:'34'.repeat(32),DB:{prepare(q){return{bind(...values){return{async first(){return sql.prepare(q).get(...values)},async run(){return{meta:{changes:sql.prepare(q).run(...values).changes}}}}}}}}}}
const login=(password='test-entry',fields={},ip='192.0.2.1')=>new Request(origin+'/access/login',{method:'POST',headers:{origin,'content-type':'application/x-www-form-urlencoded','cf-connecting-ip':ip},body:new URLSearchParams({password,...fields})});
test('password gate protects pages, scripts, room lists and direct room requests before identity is granted',async()=>{const env=await setup();const page=await worker.fetch(new Request(origin+'/?room=abc'),env);assert.equal(page.status,200);assert.match(await page.text(),/输入访问密码/);for(const path of ['/app.mjs','/vendor/three.module.min.js','/api/session','/api/rooms','/api/rooms/'+'a'.repeat(32)]){const r=await worker.fetch(new Request(origin+path,{headers:{'oai-authenticated-user-id':'owner',cookie:'bb_session='+'a'.repeat(64)}}),env);assert.equal(r.status,401,path);assert.equal(r.headers.get('cache-control'),'no-store')}assert.equal((await worker.fetch(new Request(origin),{})).status,503)});
test('valid password issues an HttpOnly signed session and preserves the invitation destination',async()=>{const env=await setup(),r=await accessGate(login('test-entry',{returnTo:'/?room=abc',remember:'yes'}),env);assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/?room=abc');const set=r.headers.get('set-cookie');assert.match(set,/HttpOnly; Secure; SameSite=Lax/);assert.match(set,/Max-Age=2592000/);assert(!set.includes('test-entry'));const token=set.split(';')[0];assert.equal(await accessGate(new Request(origin+'/api/rooms',{headers:{cookie:token}}),env),null);assert.equal((await worker.fetch(new Request(origin+'/app.mjs',{headers:{cookie:token}}),env)).status,200);const tampered=token.slice(0,-5)+'aaaaa';assert.equal((await accessGate(new Request(origin+'/api/rooms',{headers:{cookie:tampered}}),env)).status,401);assert.equal((await accessGate(new Request(origin+'/api/rooms',{headers:{cookie:token}}),{...env,ACCESS_SESSION_KEY:'56'.repeat(32)})).status,401);const redirect=await accessGate(login('test-entry',{returnTo:'//evil.example'}),env);assert.equal(redirect.headers.get('location'),'/')});
test('wrong guesses are rate limited across requests and malformed origins cannot log in',async()=>{const env=await setup();for(let i=0;i<8;i++)assert.equal((await accessGate(login('wrong'),env)).status,401);assert.equal((await accessGate(login(),env)).status,429);assert.equal((await accessGate(login('test-entry',{},'192.0.2.2'),env)).status,303);const forged=new Request(origin+'/access/login',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/x-www-form-urlencoded'},body:'password=test-entry'});assert.equal((await accessGate(forged,env)).status,403);const logout=await accessGate(new Request(origin+'/access/logout',{method:'POST',headers:{origin}}),env);assert.match(logout.headers.get('set-cookie'),/Max-Age=0/)});
