import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {Club} from '../server/club.mjs';
import {unpack,pack} from '../server/rooms.mjs';
import {adminLogin,isAdmin} from '../server/admin-auth.mjs';
import {passwordHash} from '../server/access.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const db={prepare(q){return{bind(...args){return{async first(){return sql.prepare(q).get(...args)},async run(){return{meta:{changes:sql.prepare(q).run(...args).changes}}}}}}}};return{club:new Club(db),db}}
let time=1800000000000;const id=()=>crypto.randomUUID().replaceAll('-','');
async function allow(c,auth='one'){const {player:p}=await c.session(auth,'iPad Safari',time);await c.profile(auth,{name:auth,role:1},time);await c.admin(auth,{kind:'permission',id:p.id,status:'allowed',requestId:id()},time);return p.id}

test('batch grants apply once to each player and preserve per-player audit entries',async()=>{const {club:c}=fixture();await allow(c,'admin');const ids=[await allow(c,'one'),await allow(c,'two')];const req={kind:'batch',action:'grant',ids,amount:321,requestId:id()};await c.admin('admin',req,time);await c.admin('admin',req,time);const data=await c.admin('admin',null,time);for(const pid of ids)assert.equal(data.players.find(p=>p.id===pid).bank,2321);assert.equal(data.audit.filter(a=>a.requestId===req.requestId).length,2)});
test('invalid member, duplicate id, self deletion and invalid amount roll back the whole batch',async()=>{const {club:c}=fixture();const admin=await allow(c,'admin'),one=await allow(c);for(const req of [{action:'grant',ids:[one,'missing'],amount:10},{action:'grant',ids:[one,one],amount:10},{action:'grant',ids:[one],amount:1.5},{action:'deletePlayer',ids:[one,admin]},{action:'permission',ids:[one,admin],status:'blocked'}])await assert.rejects(()=>c.admin('admin',{kind:'batch',...req,requestId:id()},time));const data=await c.admin('admin',null,time);assert.equal(data.players.find(p=>p.id===one).bank,2000);assert.equal(data.players.find(p=>p.id===one).status,'allowed')});
test('batch permissions and deletion work; closing shared room refunds remaining players once',async()=>{const {club:c}=fixture();await allow(c,'admin');const one=await allow(c),two=await allow(c,'two');await c.admin('admin',{kind:'batch',action:'permission',ids:[one,two],status:'blocked',requestId:id()},time);assert.equal((await c.session('one','',time)).player.status,'blocked');await c.admin('admin',{kind:'batch',action:'permission',ids:[one,two],status:'allowed',requestId:id()},time);const r=await c.create('one',{mode:'blackjack',capacity:4},time);await c.room(r.id,'two',{kind:'join',requestId:id()},time);await c.room(r.id,'admin',{kind:'join',requestId:id()},time);const req={kind:'batch',action:'deletePlayer',ids:[one,two],requestId:id()};await c.admin('admin',req,time);await c.admin('admin',req,time);const data=await c.admin('admin',null,time);assert.equal(data.players.length,1);assert.equal(data.rooms.length,0);assert.equal(data.players[0].bank,2000);assert.equal((await c.session('one','',time)).player.bank,0)});
