import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {Club} from '../server/club.mjs';
import {unpack,pack} from '../server/rooms.mjs';
import {adminLogin,isAdmin} from '../server/admin-auth.mjs';
import {passwordHash} from '../server/access.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const db={prepare(q){return{bind(...args){return{async first(){return sql.prepare(q).get(...args)},async run(){return{meta:{changes:sql.prepare(q).run(...args).changes}}}}}}}};return{club:new Club(db),db}}
let time=1800000000000;const id=()=>crypto.randomUUID().replaceAll('-','');
async function allow(c,auth='one'){const {player:p}=await c.session(auth,'iPad Safari',time);await c.profile(auth,{name:auth,role:1},time);await c.admin(auth,{kind:'permission',id:p.id,status:'allowed',requestId:id()},time);return p.id}
test('new devices get 2000 once, remain pending, and changing profile never resets money',async()=>{const {club:c}=fixture();const a=await c.session('one','iPad',time);assert.equal(a.player.bank,2000);assert.equal(a.player.status,'pending');await assert.rejects(()=>c.create('one',{mode:'blackjack',solo:true},time));await allow(c);let r=await c.create('one',{mode:'blackjack',solo:true,bank:999999,name:'fake',role:3},time);assert.equal(r.seats[0].bank,2000);assert.equal(r.seats[0].name,'one');assert.equal(r.seats[0].role,1);await assert.rejects(()=>c.create('one',{mode:'craps',solo:true},time));assert.equal((await c.session('one','iPad',time)).player.bank,0);assert.equal((await c.session('two','iPad',time)).player.status,'pending')});
test('grant is atomic and idempotent; suspension rejects actions from an already seated device',async()=>{const {club:c}=fixture();const p=await allow(c);const request={kind:'grant',id:p,amount:150,requestId:id()};await Promise.all([c.admin('one',request,time),c.admin('one',request,time)]);assert.equal((await c.session('one','',time)).player.bank,2150);const r=await c.create('one',{mode:'roulette',solo:true},time);await allow(c,'admin');await c.admin('admin',{kind:'permission',id:p,status:'blocked',requestId:id()},time);await assert.rejects(()=>c.room(r.id,'one',{kind:'act',action:'launch',requestId:id()},time),/停用/);await c.admin('admin',{kind:'permission',id:p,status:'allowed',requestId:id()},time);await c.room(r.id,'one',{kind:'act',action:'launch',requestId:id()},time)});
test('concurrent room creation cannot duplicate bankroll and return on lobby exit is exactly once',async()=>{const {club:c}=fixture();await allow(c);const results=await Promise.allSettled([c.create('one',{mode:'poker',capacity:4},time),c.create('one',{mode:'poker',capacity:4},time)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const r=results.find(r=>r.status==='fulfilled').value;const req={kind:'leave',requestId:id()};await c.room(r.id,'one',req,time);await c.room(r.id,'one',req,time).catch(()=>{});assert.equal((await c.session('one','',time)).player.bank,2000)});
test('single dice and roulette have no bots; other solo modes use only required seats',async()=>{for(const [mode,n] of [['craps',1],['roulette',1],['blackjack',1],['poker',4],['guandan',4]]){const {club:c}=fixture();await allow(c);const r=await c.create('one',{mode,solo:true,capacity:4},time);assert.equal(r.seats.length,n);assert.equal(r.status,'playing');assert.equal(r.solo,true)}});
test('leaving blackjack forfeits stakes, immediately releases the seat and never pays later',async()=>{const {club:c}=fixture();await allow(c);let r=await c.create('one',{mode:'blackjack',solo:true},time);r=await c.room(r.id,'one',{kind:'act',action:'bet',amount:100,seq:r.seq,requestId:id()},time);const req={kind:'leave',requestId:id()};await c.room(r.id,'one',req,time);const p=(await c.session('one','',time)).player;assert.equal(p.bank,1900);assert.equal(p.activeRoom,null);assert.equal(p.settling,false);await c.room(r.id,'one',req,time).catch(()=>{});assert.equal((await c.session('one','',time+3000000)).player.bank,1900);const next=await c.create('one',{mode:'roulette',solo:true},time+3000001);assert.equal(next.seats[0].bank,1900)});
test('every game releases immediately, including rolling dice with locked bets',async()=>{for(const mode of ['poker','craps','roulette','guandan']){const {club:c}=fixture();await allow(c);let r=await c.create('one',{mode,solo:true,capacity:4},time);let expected=2000;if(mode==='craps'){r=await c.room(r.id,'one',{kind:'act',action:'bet',key:'pass',amount:100,requestId:id()},time);r=await c.room(r.id,'one',{kind:'act',action:'roll',requestId:id()},time);expected=1900}await c.room(r.id,'one',{kind:'leave',requestId:id()},time);const p=(await c.session('one','',time)).player;assert.equal(p.activeRoom,null,mode);assert.equal(p.bank,expected,mode);assert.equal((await c.session('one','',time+3000000)).player.bank,expected,mode);await c.create('one',{mode:'blackjack',solo:true},time+3000001)}});
test('grants during a round remain in reserve and are added on the next round without resets',async()=>{const {club:c}=fixture();const id1=await allow(c);let r=await c.create('one',{mode:'blackjack',solo:true},time);await c.admin('one',{kind:'grant',id:id1,amount:321,requestId:id()},time);for(let k=1;k<45;k++)r=await c.room(r.id,'one',null,time+k*10000);assert.equal(r.status,'roundEnd');const before=r.seats[0].bank;r=await c.room(r.id,'one',{kind:'next',requestId:id()},time+450000);assert.equal(r.seats[0].bank,before+321);assert.equal((await c.session('one','',time+450000)).player.bank,0)});
test('zero balance is not replenished and offline status expires',async()=>{const {club:c}=fixture();await allow(c);await c.change(s=>{s.players[0].bank=0});await assert.rejects(()=>c.create('one',{mode:'blackjack',solo:true},time),/筹码不足/);assert.equal((await c.admin('one',null,time+46000)).players[0].online,false)});
test('administrator cookie is device-bound, expires, resists tampering and login is rate limited',async()=>{const {db}=fixture(),salt='af'.repeat(16),env={DB:db,ACCESS_SESSION_KEY:'ab'.repeat(32),ADMIN_PASSWORD_HASH:salt+':'+await passwordHash('owner-test-password',salt)},req=new Request('https://example.test/api/admin/login');const cookie=await adminLogin(req,env,'owner-device','owner-test-password',time);const signed=new Request(req,{headers:{cookie:cookie.split(';')[0]}});assert(await isAdmin(signed,env,'owner-device',time));assert.equal(await isAdmin(signed,env,'another-device',time),false);assert.equal(await isAdmin(signed,env,'owner-device',time+9*3600000),false);assert.equal(await isAdmin(new Request(req,{headers:{cookie:cookie.split(';')[0]+'a'}}),env,'owner-device',time),false);for(let n=0;n<8;n++)await assert.rejects(()=>adminLogin(req,env,'owner-device','wrong',time));await assert.rejects(()=>adminLogin(req,env,'owner-device','owner-test-password',time),/15/)});
test('server-controlled solo skill spends chips once and never exposes the deck',async()=>{const {club:c}=fixture();await allow(c);let r=await c.create('one',{mode:'poker',capacity:4,solo:true,skills:true},time);await c.change(s=>{const room=unpack(s.rooms[r.id]);room.game.turn=0;s.rooms[r.id]=pack(room)});r=await c.room(r.id,'one',null,time);const before=r.game.players[0].chips;const key=id();r=await c.room(r.id,'one',{kind:'act',action:'skill',index:0,seq:r.seq,requestId:key},time);assert.equal(r.game.players[0].chips,before-200);assert.equal(r.skill.used,true);assert(!('deck' in r.game));await assert.rejects(()=>c.room(r.id,'one',{kind:'act',action:'skill',index:0,seq:r.seq,requestId:id()},time));r=await c.room(r.id,'one',{kind:'act',action:'skill',index:0,requestId:key},time);assert.equal(r.game.players[0].chips,before-200)});

test('idle rooms expire despite polling, refund once and release seats',async()=>{for(const mode of ['poker','blackjack','roulette','craps','guandan']){const {club:c}=fixture();await allow(c);let r=await c.create('one',{mode,solo:true,capacity:4},time);for(let n=1;n<=19;n++)await c.session('one','',time+n*60000);const expected=await c.change(s=>s.players[0].bank+c.tableTotal(s,s.players[0]));const closed=await c.room(r.id,'one',null,time+1200000);assert.equal(closed.closed,true,mode);const p=(await c.session('one','',time+1200001)).player;assert.equal(p.activeRoom,null);assert.equal(p.bank,expected);assert.equal((await c.list('one',time+1200002)).rooms.length,0)}});
test('real successful actions extend inactivity but duplicate retries do not',async()=>{const {club:c}=fixture();await allow(c);const r=await c.create('one',{mode:'craps',solo:true},time);const req={kind:'act',action:'bet',key:'pass',amount:100,requestId:id()};await c.room(r.id,'one',req,time+600000);await c.room(r.id,'one',req,time+1100000);assert.equal((await c.list('one',time+1200000)).rooms.length,1);assert.equal((await c.list('one',time+1800000)).rooms.length,0);assert.equal((await c.session('one','',time+1800001)).player.bank,2000)});
test('administrator closes rooms idempotently and deletes player without repeat welcome grant',async()=>{const {club:c}=fixture();await allow(c,'admin');const playerId=await allow(c);const r=await c.create('one',{mode:'craps',solo:true},time);await c.room(r.id,'one',{kind:'act',action:'bet',key:'pass',amount:100,requestId:id()},time);const close={kind:'closeRoom',id:r.id,requestId:id()};await c.admin('admin',close,time);await c.admin('admin',close,time);assert.equal((await c.session('one','',time)).player.bank,2000);await c.create('one',{mode:'roulette',solo:true},time);const del={kind:'deletePlayer',id:playerId,requestId:id()};await c.admin('admin',del,time);await c.admin('admin',del,time);const a=await c.admin('admin',null,time);assert.equal(a.rooms.length,0);assert(!a.players.some(p=>p.id===playerId));const renewed=(await c.session('one','',time)).player;assert.equal(renewed.bank,0);assert.equal(renewed.status,'pending');assert.equal(renewed.name,'');await assert.rejects(()=>c.admin('admin',{kind:'deletePlayer',id:a.actorId,requestId:id()},time),/不能删除/)});

test('partial rooms start and late joins reserve capacity without touching active hands',async()=>{
 for(const mode of ['poker','blackjack','roulette','craps']){
 const {club:c,db}=fixture();for(const a of ['one','two','three','four','five'])await allow(c,a);
 let r=await c.create('one',{mode,capacity:4},time);
 r=await c.room(r.id,'two',{kind:'join',requestId:id()},time);
 r=await c.room(r.id,'two',{kind:'ready',ready:true,requestId:id()},time);
 r=await c.room(r.id,'one',{kind:'start',requestId:id()},time);assert.equal(r.status,'playing');assert.equal(r.seats.length,2);
 assert.equal((await c.list('three',time)).rooms[0].joinable,true);
 const joined=await c.room(r.id,'three',{kind:'join',requestId:id()},time);assert.equal(joined.waiting,true);assert.equal(joined.game,undefined);
 await assert.rejects(()=>c.room(r.id,'three',{kind:'act',action:'skill',seq:joined.seq,requestId:id()},time),/等待/);
 assert.equal((await c.session('three','',time)).players.find(p=>p.name==='three').totalChips,2000);
 const active=await c.room(r.id,'one',null,time);assert.equal(active.seats.length,2);
 await c.room(r.id,'four',{kind:'join',requestId:id()},time);
 assert.equal((await c.list('five',time)).rooms[0].joinable,false);
 await assert.rejects(()=>c.room(r.id,'five',{kind:'join',requestId:id()},time),/已满/);
 await c.room(r.id,'four',{kind:'leave',requestId:id()},time);assert.equal((await c.session('four','',time)).player.bank,2000);
 if(mode==='craps'){
 await c.room(r.id,'one',{kind:'act',action:'roll',requestId:id()},time);
 for(const dt of [60000,64000,67000])await c.room(r.id,'one',null,time+dt);
 const seated=await c.room(r.id,'three',null,time+67001);assert.equal(seated.waiting,false);assert.equal(seated.game.others.length,3);assert.equal(seated.game.table.bank,2000);
 }else{
 // Complete a round boundary without altering the waiting entrant's balance.
 const row=await db.prepare('SELECT version,state FROM club_state WHERE id = 1').bind().first();const state=JSON.parse(row.state),raw=unpack(state.rooms[r.id]);
 raw.status='roundEnd';raw.reviewUntil=time;raw.game.done=true;raw.seats.forEach(s=>s.ready=true);state.rooms[r.id]=pack(raw);
 await db.prepare('UPDATE club_state SET state = ?, version = version + 1 WHERE id = 1 AND version = ?').bind(JSON.stringify(state),row.version).run();
 const seated=await c.room(r.id,'three',null,time+1);assert.equal(seated.waiting,false);assert.equal(seated.game.players.length,3);assert.equal(seated.seats.length,3);
 }
 }
});

test('nickname-only admission stays pending until approved, without exposing the directory',async()=>{const {club:c}=fixture();await allow(c,'admin');const session=await c.session('new','phone',time);assert.deepEqual(session.players,[]);const {player:p}=await c.profile('new',{name:'New friend',status:'allowed',bank:99999},time);assert.equal(p.status,'pending');assert.equal(p.bank,2000);assert.equal(p.role,0);await assert.rejects(()=>c.list('new',time));await c.admin('admin',{kind:'permission',id:p.id,status:'allowed',requestId:id()},time);assert.equal((await c.session('new','phone',time)).player.status,'allowed');assert.deepEqual((await c.list('new',time)).rooms,[]);await c.profile('new',{name:'New friend',role:2},time);assert.equal((await c.session('new','phone',time)).player.role,2)});
