import test from 'node:test';import assert from 'node:assert/strict';
import {RoomGame,prepareRoomView} from '../dist/room-game.mjs';
test('poker and blackjack can render face-up cards without ever loading Guandan',async()=>{for(const mode of ['poker','blackjack']){await prepareRoomView(mode);const view=Object.create(RoomGame.prototype);assert.match(view.card({r:13,s:'♠'}),/>K</);assert.match(view.card({r:5,s:'♥'}),/>5</)}});
import {createRoom,command,tick,snapshot} from '../server/rooms.mjs';
import {Rooms} from '../dist/multiplayer.mjs';
function surface(){const nodes=new Map(),get=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',value:'40',insertAdjacentHTML(_,html){this.innerHTML+=html}});return nodes.get(s)},buttons=[];const host={querySelectorAll(selector){if(selector!=='[data-action]'&&selector!=='[data-stake]')return[];const key=selector==='[data-action]'?'action':'stake';const parsed=[];for(const match of get('.mp-controls').innerHTML.matchAll(new RegExp('<button[^>]*data-'+key+'="([^"]+)"[^>]*>','g'))){const b={dataset:{[key]:match[1]},disabled:/\bdisabled\b/.test(match[0])};parsed.push(b);buttons.push(b)}return parsed}};return{get,host,buttons}}
for(const mode of ['poker','blackjack'])test(mode+' enables a real action after dealing and sends it to the game engine',async()=>{await prepareRoomView(mode);const r=createRoom('human',{mode,solo:true,capacity:mode==='poker'?4:1,name:'Human',role:0},1000);r.solo=true;if(mode==='poker')for(let i=0;i<3;i++)command(r,'human',{kind:'addBot'},1000);command(r,'human',{kind:'start'},1000);let now=2000;
 if(mode==='poker')r.game.turn=0;else {r.game.deck=Array.from({length:60},(_,i)=>({r:i%2?5:2,s:'♣',id:'c'+i}));command(r,'human',{kind:'act',action:'bet',amount:50,seq:r.seq},now);for(let i=0;i<20&&r.game.phase!=='players';i++){now+=1000;tick(r,now)}assert.equal(r.game.phase,'players')}
 const dom=surface(),view=Object.create(RoomGame.prototype),previous=globalThis.document;globalThis.document={querySelector:()=>null};try{let sent=0;Object.assign(view,{order:r.seats.map((_,i)=>i),q:dom.get,host:dom.host,now:()=>now,send:async data=>{command(r,'human',{kind:'act',seq:r.seq,...data},now);sent++}});view.renderTable(snapshot(r,'human',now));assert.match(dom.get('.mp-own').innerHTML,/gd-card/);const button=dom.buttons.find(b=>b.dataset.action===(mode==='poker'?'call':'hit'));assert(button);assert.equal(button.disabled,false);assert.equal(typeof button.onclick,'function');const seq=r.seq;await button.onclick();assert.equal(sent,1);assert(r.seq>seq);view.renderTable(snapshot(r,'human',now));}finally{globalThis.document=previous}});
test('failed view rendering clears the unchanged token and allows same-sequence recovery',()=>{let attempts=0;const client=Object.assign(Object.create(Rooms.prototype),{view:{apply(){if(++attempts===1)throw Error('transient')}}}),r={seq:1,revision:'1:1111'};assert.throws(()=>client.renderView(r));assert.equal(r.revision,undefined);assert.equal(client.renderFailed,true);client.renderView(r);assert.equal(client.renderFailed,false);assert.equal(attempts,2)});
