import assert from 'node:assert/strict';
import {Guandan,GuandanMatch,newDeck,interpretations,moves,beats,chooseMove,wild,strength} from '../dist/guandan.mjs';
let id=0;const card=(r,s='♠')=>({id:id++,r,s}),cards=(rs,s='♠')=>rs.map(r=>card(r,s));
const type=(cs,t,level=2)=>{const m=interpretations(cs,level).find(m=>m.type===t);assert(m,'missing '+t+' '+cs.map(c=>c.r));return m};
const deck=newDeck();assert.equal(deck.length,108);assert.equal(new Set(deck.map(c=>c.id)).size,108);for(let r=2;r<=16;r++)assert.equal(deck.filter(c=>c.r===r).length,r>14?2:8);
for(const[t,rs]of[['single',[6]],['pair',[6,6]],['triple',[6,6,6]],['full',[6,6,6,8,8]],['straight',[2,3,4,5,6]],['pairs',[2,2,3,3,4,4]],['plate',[2,2,2,3,3,3]],['bomb',[9,9,9,9]],['flush',[10,11,12,13,14]],['kings',[15,15,16,16]]])type(cards(rs),t);
for(const[t,rs]of[['straight',[14,2,3,4,5]],['pairs',[14,14,2,2,3,3]],['plate',[14,14,14,2,2,2]]])type(cards(rs),t);
assert.equal(interpretations(cards([13,14,2,3,4]),2).length,0);assert.equal(interpretations(cards([15,15,16]),2).length,0);assert.equal(interpretations([card(15),card(2,'♥')],2).length,0);assert.equal(interpretations([card(16),card(2,'♥')],2).length,0);
const w1=card(2,'♥'),w2=card(2,'♥');assert.equal(interpretations([w1],2).length,1);assert.equal(type([w1,w2],'pair').rank,2);type([...cards([3,4,5,6],'♦'),w1],'flush');type([...cards(Array(8).fill(9)),w1,w2],'bomb');
const ambiguity=interpretations([...cards([5,5,6,6]),w1],2).filter(m=>m.type==='full');assert.deepEqual(ambiguity.map(m=>m.rank).sort(),[5,6]);
const bomb4=type(cards([14,14,14,14]),'bomb'),bomb5=type(cards([3,3,3,3,3]),'bomb'),sf=type(cards([2,3,4,5,6]),'flush'),bomb6=type(cards([3,3,3,3,3,3]),'bomb'),kings=type(cards([15,15,16,16]),'kings');assert(beats(bomb5,bomb4));assert(beats(sf,bomb5));assert(beats(bomb6,sf));assert(beats(kings,bomb6));assert(!beats(sf,bomb6));assert(!beats(bomb4,bomb4));assert(beats(type(cards([2]),'single'),type(cards([14]),'single')));assert(!beats(type(cards([3,3]),'pair'),type(cards([2]),'single')));
const round=new Guandan({hands:[cards([3]),cards([4,5]),cards([6,7]),cards([8,9])]});round.act(0,[round.hands[0][0].id]);assert.equal(round.turn,1);round.act(1,[]);round.act(2,[]);round.act(3,[]);assert.equal(round.turn,2);assert.equal(round.target,null);assert.throws(()=>round.act(2,[]));assert.throws(()=>round.act(1,[round.hands[1][0].id]));
const teamed=new Guandan({hands:[cards([3,8]),cards([4,5]),cards([6,7]),cards([9,10])]});teamed.act(0,[teamed.hands[0][0].id]);teamed.act(1,[teamed.hands[1][0].id]);teamed.act(2,[]);teamed.act(3,[]);teamed.act(0,[]);assert.equal(teamed.turn,1);assert.equal(teamed.target,null);
function seeded(s){return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
let actions=0,tributeRounds=0;
for(let seed=1;seed<=8;seed++){const match=new GuandanMatch(seeded(seed));for(let round=0;round<5;round++){const g=match.start();if(g.returns.length){tributeRounds++;assert.throws(()=>g.act(g.turn,[]));while(g.returns.length)match.autoReturn()}assert(g.hands.every(h=>h.length===27));assert.equal(new Set(g.hands.flat().map(c=>c.id)).size,108);let steps=0;while(!g.done){assert(++steps<700,'game must terminate');const snapshot=g.snapshot(g.turn);assert(!('hands'in snapshot));assert.equal(snapshot.hand.length,g.hands[g.turn].length);const m=chooseMove(snapshot);if(m){assert(interpretations(m.cards,g.level,g.target).some(x=>x.key===m.key));const ids=m.cards.map(c=>c.id);assert.equal(new Set(ids).size,ids.length)}g.act(g.turn,m?.cards.map(c=>c.id)||[],m?.key);actions++;assert.equal(g.hands.flat().length+g.actions.reduce((n,a)=>n+a.cards.length,0),108)}assert.equal(new Set(g.finish).size,4);const result=match.settle();assert([1,2,3].includes(result.gain));assert.equal(result.team,g.finish[0]%2);assert.equal(match.settle(),result);if(match.champion!==null)break}}
for(const[order,gain]of[[[0,2,1,3],3],[[0,1,2,3],2],[[0,1,3,2],1]]){const m=new GuandanMatch();m.start();m.game.done=true;m.game.finish=order;assert.equal(m.settle().gain,gain)}
console.log({games:40,actions,tributeRounds,result:'all passed',checks:'108 unique cards, all patterns, wildcards, hierarchy, passes, teammate lead, legal private AI, complete games, tribute conservation, upgrades'});
