import test from 'node:test';import assert from 'node:assert/strict';import {createRoom,command,tick,snapshot,pack,unpack} from '../server/rooms.mjs';
const now=1800000000000;
function humans(mode,n=4){const r=createRoom('p0',{mode,capacity:4,name:'玩家0',role:0},now);for(let i=1;i<n;i++){command(r,'p'+i,{kind:'join',name:'玩家'+i,role:i%4},now);command(r,'p'+i,{kind:'ready',ready:true},now)}command(r,'p0',{kind:'start'},now);return r}
function leave(r,auth){command(r,auth,{kind:'leave'},now+1);assert(r.seats.every(s=>!s.bot));assert.equal(snapshot(r,auth,now).you,-1);return unpack(pack(r))}
test('poker retains indices during a hand, then continues with only remaining real players',()=>{let r=leave(humans('poker'),'p2');assert(r.seats[2].departed);for(let n=0;n<100&&r.status==='playing';n++){if(r.game.pending.size)command(r,r.seats[r.game.turn].auth,{kind:'act',action:'call',seq:r.seq},now+100);else tick(r,now+65000)}assert.equal(r.status,'roundEnd');const round=r.round;for(const s of r.seats.filter(s=>s.auth))command(r,s.auth,{kind:'next'},r.reviewUntil+1);assert.equal(r.round,round+1);assert.equal(r.seats.length,3);assert(r.seats.every(s=>s.auth&&!s.bot));assert.equal(r.game.players.length,3)});
test('blackjack and roulette wait for real readiness and never substitute departed players',()=>{for(const mode of ['blackjack','roulette']){let r=leave(humans(mode),'p2');if(mode==='roulette')command(r,'p0',{kind:'act',action:'launch',seq:r.seq},now+100);for(let n=0;n<100&&r.status==='playing';n++)tick(r,now+(n+1)*65000);assert.equal(r.status,'roundEnd',mode);assert.equal(r.round,1);for(const s of r.seats.filter(s=>s.auth))command(r,s.auth,{kind:'next'},r.reviewUntil+1);assert.equal(r.seats.length,3);assert(r.seats.every(s=>s.auth&&!s.bot));assert.equal(r.round,2)}});
test('last remaining friend goes to preparation instead of getting a bot or readiness error',()=>{let r=humans('poker',2);r=leave(r,'p1');assert.equal(r.status,'roundEnd');command(r,'p0',{kind:'next'},r.reviewUntil+1);assert.equal(r.status,'lobby');assert.equal(r.seats.length,1);assert.equal(r.game,null);command(r,'p3',{kind:'join',name:'新人',role:3},r.reviewUntil+2);command(r,'p3',{kind:'ready',ready:true},r.reviewUntil+2);command(r,'p0',{kind:'start'},r.reviewUntil+3);assert.equal(r.status,'playing');assert.equal(r.seats.length,2)});
test('guandan and bigtwo immediately return to a four-seat lobby and require a new human',()=>{for(const mode of ['guandan','bigtwo']){let r=leave(humans(mode),'p1');assert.equal(r.status,'lobby');assert.equal(r.seats.length,3);assert.equal(r.game,null);assert.throws(()=>command(r,'p0',{kind:'start'},now+100));command(r,'p4',{kind:'join',name:'补位真人',role:1},now+100);for(const s of r.seats)command(r,s.auth,{kind:'ready',ready:true},now+100);command(r,'p0',{kind:'start'},now+100);assert.equal(r.status,'playing');assert(r.seats.every(s=>s.auth&&!s.bot))}});
test('craps hands the dice to a remaining human and safely drops old slots after the shared roll',()=>{for(const rolling of [false,true]){let r=humans('craps');if(rolling)command(r,'p0',{kind:'act',action:'roll',seq:r.seq},now+1);r=leave(r,'p0');assert.equal(r.host,'p1');assert.equal(r.seats[r.game.roller].auth,'p1');if(rolling){for(let n=0;n<4;n++)tick(r,r.nextAt+1)}assert.equal(r.seats.length,3);assert.equal(r.game.tables.length,3);assert(r.seats.every(s=>s.auth&&!s.bot));if(!rolling){tick(r,now+600000);assert.equal(r.game.phase,'bets')}}});
test('a departed slot does not block a new real player joining a full table',()=>{const r=leave(humans('blackjack'),'p1');command(r,'p4',{kind:'join',name:'新人',role:0},now+100);assert.equal(r.seats.filter(s=>!s.departed).length,4);assert.equal(snapshot(r,'p4',now).waiting,true);assert.throws(()=>command(r,'p5',{kind:'join',name:'超额',role:0},now+100))});
