import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {gzipSync} from 'node:zlib';
import {Club} from '../server/club.mjs';
import {staticResponse} from '../server/static-response.mjs';
import {RoomGame} from '../dist/room-game.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));let writes=0;const db={prepare(q){return{bind(...args){return{async first(){return sql.prepare(q).get(...args)},async run(){writes++;return{meta:{changes:sql.prepare(q).run(...args).changes}}}}}}}};return{club:new Club(db),writes:()=>writes}}
const now=1800000000000,id=()=>crypto.randomUUID().replaceAll('-','');
async function allow(c,name){const {player}=await c.session(name,'test',now);await c.profile(name,{name},now);await c.admin(name,{kind:'permission',id:player.id,status:'allowed',requestId:id()},now)}
test('idle reads skip UPDATE; the throttled heartbeat writes only once in ten seconds',async()=>{const f=fixture(),c=f.club;await allow(c,'one');const r=await c.create('one',{mode:'craps',solo:true},now),v=await c.room(r.id,'one',null,now);const baseline=f.writes();for(let i=1;i<=10;i++){const result=await c.room(r.id,'one',null,now+i*900,v.revision);assert.equal(result.unchanged,true);assert.equal(result.game,undefined);await c.list('one',now+i*900)}assert.equal(f.writes(),baseline);await c.room(r.id,'one',null,now+10000,v.revision);assert.equal(f.writes(),baseline+1)});
test('polling one room does not run another room AI',async()=>{const f=fixture(),c=f.club;await allow(c,'one');await allow(c,'two');const r=await c.create('one',{mode:'poker',solo:true,capacity:4},now);const other=await c.create('two',{mode:'craps',solo:true},now);const before=await c.change(s=>s.rooms[r.id]);await c.room(other.id,'two',null,now+100000);await c.list('two',now+100000);assert.equal(await c.change(s=>s.rooms[r.id]),before)});
test('unchanged shortcut still checks permission and expires/refunds idle rooms',async()=>{const f=fixture(),c=f.club;await allow(c,'one');let r=await c.create('one',{mode:'craps',solo:true},now);r=await c.room(r.id,'one',null,now);const player=(await c.session('one','',now)).player;await allow(c,'admin');await c.admin('admin',{kind:'permission',id:player.id,status:'blocked',requestId:id()},now);await assert.rejects(()=>c.room(r.id,'one',null,now,r.revision),/停用/);await c.admin('admin',{kind:'permission',id:player.id,status:'allowed',requestId:id()},now);assert.equal((await c.room(r.id,'one',null,now+1200000,r.revision)).closed,true);assert.equal((await c.session('one','',now+1200001)).player.bank,2000)});
test('static assets revalidate, hashed assets are immutable and gzip has a plain fallback',async()=>{const data='export const test=42;',asset={hash:'abc',type:'text/javascript',gzip:true,size:data.length,data:gzipSync(data).toString('base64')},assets={'/built/app-ABC123.js':asset,'/index.html':{...asset,type:'text/html'}};const url='https://example.test/built/app-ABC123.js';const res=staticResponse(new Request(url),assets);assert.match(res.headers.get('cache-control'),/immutable/);assert.equal(await res.text(),data);const hit=staticResponse(new Request(url,{headers:{'if-none-match':res.headers.get('etag')}}),assets);assert.equal(hit.status,304);assert.equal(await hit.text(),'');assert.equal(staticResponse(new Request(url,{headers:{'accept-encoding':'gzip, deflate, br'}}),assets).headers.get('content-encoding'),'gzip');assert.match(staticResponse(new Request('https://example.test/'),assets).headers.get('cache-control'),/must-revalidate/);assert.equal(staticResponse(new Request('https://example.test/missing'),assets).status,404)});
test('identical controls preserve live input nodes',()=>{let writes=0,markup='';const node={set innerHTML(value){writes++;markup=value},get innerHTML(){return markup}},view=Object.assign(Object.create(RoomGame.prototype),{q:()=>node});view.updateControls('<input value="40">');view.updateControls('<input value="40">');assert.equal(writes,1);view.updateControls('<button disabled>等待</button>');assert.equal(writes,2)});
