import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {Club} from '../server/club.mjs';import {pack,unpack} from '../server/rooms.mjs';
const now=1800000000000,id=()=>crypto.randomUUID().replaceAll('-','');
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const db={prepare(q){return{bind(...args){return{async first(){return sql.prepare(q).get(...args)},async run(){return{meta:{changes:sql.prepare(q).run(...args).changes}}}}}}}};return new Club(db)}
async function allow(c,auth='one'){const {player}=await c.session(auth,'test',now);await c.profile(auth,{name:auth},now);await c.admin(auth,{kind:'permission',id:player.id,status:'allowed',requestId:id()},now);return player.id}
async function act(c,r,action,extra={},time=now){return c.room(r.id,'one',{kind:'act',action,...extra,requestId:id()},time)}
test('stats exclude grants, transfers and refunds; leaderboard includes offline players and ties',async()=>{const c=fixture(),p=await allow(c);await allow(c,'two');let s=await c.stats('one',now+46000);assert.equal(s.chips.length,2);assert(s.chips.every(p=>!p.online&&p.rank===1));await c.admin('one',{kind:'grant',id:p,amount:500,requestId:id()},now);let r=await c.create('one',{mode:'roulette',solo:true},now);s=await c.stats('one',now);assert.equal(s.chips.find(p=>p.name==='one').value,2500);assert.equal(s.games.find(g=>g.mode==='roulette').rounds,0);await c.room(r.id,'one',{kind:'leave',requestId:id()},now);assert.equal((await c.stats('one',now)).games.reduce((n,g)=>n+g.net,0),0);assert(!JSON.stringify(s).includes('auth'))});
test('roulette settlement records net once, persists across polls, and ignores next-round grants',async()=>{const c=fixture(),p=await allow(c);let r=await c.create('one',{mode:'roulette',solo:true},now);r=await act(c,r,'bet',{key:'n1',amount:10});r=await act(c,r,'launch');await c.change(s=>{const room=unpack(s.rooms[r.id]);room.game.pocket='1';s.rooms[r.id]=pack(room)});await c.room(r.id,'one',null,now+20000);let a=(await c.stats('one',now+20000)).games.find(g=>g.mode==='roulette');assert.deepEqual([a.net,a.best,a.rounds],[350,350,1]);await c.room(r.id,'one',null,now+23000);a=(await c.stats('one',now+23000)).games.find(g=>g.mode==='roulette');assert.equal(a.rounds,1);await c.admin('one',{kind:'grant',id:p,amount:100,requestId:id()},now+23000);r=await c.room(r.id,'one',{kind:'next',requestId:id()},now+24000);r=await act(c,r,'bet',{key:'n2',amount:20},now+24000);r=await act(c,r,'launch',{},now+24000);await c.change(s=>{const room=unpack(s.rooms[r.id]);room.game.pocket='1';s.rooms[r.id]=pack(room)});await c.room(r.id,'one',null,now+44000);a=(await c.stats('one',now+44000)).games.find(g=>g.mode==='roulette');assert.deepEqual([a.net,a.best,a.rounds],[330,350,2])});
test('departed roulette and blackjack stakes count as loss exactly once',async()=>{for(const mode of ['roulette','blackjack']){const c=fixture();await allow(c);let r=await c.create('one',{mode,solo:true},now);r=await act(c,r,'bet',{key:'red',amount:100,seq:r.seq});await c.room(r.id,'one',{kind:'leave',requestId:id()},now);let a=(await c.stats('one',now)).games.find(g=>g.mode===mode);assert.deepEqual([a.net,a.best,a.rounds],[-100,0,1]);await c.session('one','test',now+30000);a=(await c.stats('one',now+30000)).games.find(g=>g.mode===mode);assert.equal(a.rounds,1)}});
test('craps uses each roll net, not returned or carried stakes',async()=>{const c=fixture();await allow(c);let r=await c.create('one',{mode:'craps',solo:true},now);r=await act(c,r,'bet',{key:'pass',amount:100});r=await act(c,r,'roll');await c.change(s=>{const room=unpack(s.rooms[r.id]);room.game.roll.dice=[3,4];s.rooms[r.id]=pack(room)});await c.room(r.id,'one',null,now+60000);await c.room(r.id,'one',null,now+64000);const a=(await c.stats('one',now+64000)).games.find(g=>g.mode==='craps');assert.deepEqual([a.net,a.best,a.rounds],[100,100,1]);await c.room(r.id,'one',null,now+67000);assert.equal((await c.stats('one',now+67000)).games.find(g=>g.mode==='craps').rounds,1)});

test('cross-game single-settlement rankings keep gains and losses separate with game labels',async()=>{
 const {collectStats,statsView}=await import('../server/player-stats.mjs');
 const state={players:[{auth:'a',id:'a',name:'自己的全名',bank:2000,seen:now},{auth:'b',id:'b',name:'朋友的全名',bank:2000,seen:now}]};
 const room={pendingStats:[{auth:'a',mode:'poker',net:400,at:now},{auth:'a',mode:'poker',net:-900,at:now},{auth:'a',mode:'poker',net:-100,at:now},{auth:'a',mode:'blackjack',net:600,at:now},{auth:'b',mode:'roulette',net:500,at:now},{auth:'b',mode:'roulette',net:-1200,at:now}]};
 collectStats(state,room);collectStats(state,room);
 const data=statsView(state,state.players[0],()=>0,now);
 assert.deepEqual(data.profitRanks.map(p=>[p.mode,p.value,p.rank]),[['blackjack',600,1],['roulette',500,2],['poker',400,3]]);
 assert.deepEqual(data.lossRanks.map(p=>[p.mode,p.value,p.rank]),[['roulette',1200,1],['poker',900,2]]);
 assert.equal(data.chips.find(p=>p.id==='a').name,'自己的全名');assert.equal(data.chips.find(p=>p.id==='b').name,'朋友***');
 const {statsContent}=await import('../dist/player-stats-ui.mjs');
 const own={id:'a',bank:2000,tableBank:0};const win=statsContent(data,own,'best','profit'),loss=statsContent(data,own,'best','loss');
 assert(!win.includes('data-stat-game'));assert(win.includes('21 点')&&win.includes('+600'));assert(loss.includes('美国轮盘')&&loss.includes('−1,200'));assert(!loss.includes('+500'));
});
