import test from 'node:test';
import assert from 'node:assert/strict';
import {Poker} from '../dist/poker.mjs';
import {createRoom,command,tick,snapshot,pack,unpack} from '../server/rooms.mjs';
import {RoomGame,seatOrder} from '../dist/room-game.mjs';
const now=1700000000000;
function allIn(){const g=new Poker([100,100,100,100]);g.act(3,'fold');g.act(0,'allin');g.act(1,'fold');return g}
function room(g){const r=createRoom('host',{mode:'poker',capacity:4,role:0},now);for(let i=1;i<4;i++)command(r,'host',{kind:'addBot'},now);r.game=g;r.status='playing';r.round=1;return r}
test('heads-up cards stay private until the all-in call is complete; no premature payout',()=>{let r=room(allIn());assert(!r.game.runout);assert.deepEqual(snapshot(r,'host').game.players[2].cards,[null,null]);r.seats[2].auth='caller';r.seats[2].bot=false;command(r,'caller',{kind:'act',action:'call',seq:r.seq},now);assert(r.game.runout);assert.equal(r.game.board.length,0);assert.equal(r.game.done,false);assert.equal(r.nextAt,now+2200);assert(!r.game.paid);r=unpack(pack(r));for(const auth of['host','caller']){const v=snapshot(r,auth);assert(v.game.runout);assert(v.game.players[0].cards.every(Boolean));assert(v.game.players[2].cards.every(Boolean));assert.deepEqual(v.game.players[3].cards,[null,null])}assert(!tick(r,now+2199));for(const [step,length]of [[1,3],[2,4],[3,5]]){tick(r,now+step*2200);assert.equal(r.game.board.length,length);assert(!r.game.done);assert(r.game.runout);assert(!r.game.paid)}tick(r,now+8800);assert(r.game.done);assert.equal(r.status,'roundEnd');assert.equal(r.game.players.reduce((n,p)=>n+p.chips,0),400);assert.equal(r.game.paid.reduce((a,b)=>a+b,0),210)});
test('ordinary heads-up betting and unresolved multiway side pots do not expose cards',()=>{const g=new Poker([100,100,100,100]);g.act(3,'fold');g.act(0,'fold');g.act(1,'call');g.act(2,'check');assert(!g.runout);g.advance();assert(!g.runout);const h=new Poker([100,100,100,100]);h.act(3,'allin');h.act(0,'call');assert(!h.runout);h.act(1,'fold');assert(!h.runout);h.act(2,'call');assert(h.runout);const side=new Poker([200,200,100,100]);side.act(3,'allin');side.act(0,'call');side.act(1,'call');side.act(2,'fold');assert(!side.runout,'two deep stacks still have betting decisions')});
test('room comparison opens before the flop, with no action buttons or winner markers',()=>{const g=allIn();g.act(2,'call');const r=room(g),nodes=new Map(),q=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:''});return nodes.get(s)};let view;const ui=Object.assign(Object.create(RoomGame.prototype),{q,order:seatOrder(4,0),now:()=>now,scene:{sync:v=>view=v},host:{querySelectorAll:()=>[]}});ui.renderTable(snapshot(r,'host',now));assert(view.runout);assert(!view.done);assert.deepEqual(view.winningCards,[]);assert.deepEqual(view.winningSeats,[]);assert.equal(q('.mp-controls').innerHTML,'');assert.equal(q('.mp-result').innerHTML,'');assert.match(q('.mp-phase').innerHTML,/全下摊牌/);assert.match(q('.mp-labels').innerHTML,/data-at-head="false" data-seat-label="0"/)});
