import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../dist/vendor/three.module.min.js';
import {BlackjackTable,blackjackLayout} from '../dist/room-game.mjs';
import {PokerTavern,HERO_CARDS} from '../dist/poker-tavern.mjs';
import {Guandan3D} from '../dist/guandan3d.mjs';
test('projected head labels remain inside the scene below the reserved navigation on tablet and desktop',()=>{const raf=globalThis.requestAnimationFrame;globalThis.requestAnimationFrame=()=>0;try{for(const [w,h,header]of [[1024,768,82],[1366,1024,82],[834,1194,104],[1920,1080,82]]){const t=scene(5,BlackjackTable);t.container.clientWidth=w;t.container.clientHeight=h-header;t.clock={getDelta:()=>.016};t.hands??=[];t.dealerSeat=5;for(let seat=1;seat<=5;seat++){const rig=t.avatar(123+seat);rig.seat=seat;t.rigs.push(rig);t.scene.add(rig.group)}t.resize();const labels=new Map();for(const rig of t.rigs)labels.set(rig.seat,{dataset:{atHead:'true'},offsetWidth:132,offsetHeight:74,style:{},classList:{toggle(){}}});t.container.querySelector=s=>labels.get(Number(s.match(/data-seat-label="(\d+)"/)?.[1]))??null;t.frame();assert.equal(labels.size,5);for(const label of labels.values()){assert(parseFloat(label.style.top)-label.offsetHeight>=8);assert(parseFloat(label.style.left)-label.offsetWidth/2>=8)}}}finally{globalThis.requestAnimationFrame=raf}});
test('voxel lighting stays at its flame sources and paper edges retain card contact geometry',()=>{const t=scene();const lamps=t.roomArchitecture.children.filter(o=>o.userData.voxelSource);assert.equal(lamps.length,0);const halos=t.roomArchitecture.children.filter(o=>o.userData.candleHalos);assert.equal(halos.length,1);assert.equal(halos[0].count,24);t.roomArchitecture.traverse(o=>{if(o.material)assert(!o.material.transmission)});const card=t.makeCard(HERO_CARDS.hand[0]);assert.equal(card.children[0].scale.z,.018);assert.equal(card.children[0].material.roughness,.72);assert.equal(card.userData.face.material.roughness,.84);assert(card.children[0].material.map.isDataTexture);assert(t.roomArchitecture.children.some(o=>o.material?.emissiveIntensity===.48));const gd=scene(4,Guandan3D);assert(!gd.potProp);assert(!gd.seatLines);});
function scene(count=4,Type=PokerTavern){const t=Object.create(Type.prototype);Object.assign(t,{seatCount:count,mode:'poker',role:0,alive:true,reduced:true,elapsed:0,tweens:[],poseTweens:[],effects:[],rigs:[],materials:new Map(),textures:new Map(),cardObjects:new Map(),lastBoardCount:0,boxGeo:new T.BoxGeometry(1,1,1),scene:new T.Scene(),container:{clientWidth:1600,clientHeight:1000,querySelector(){return null}},renderer:{setSize(){},render(){}},camera:new T.PerspectiveCamera(49,1.6,.07,40)});t.texture=()=>new T.Texture();t.textTexture=()=>new T.Texture();t.faceTexture=()=>new T.Texture();t.feltTexture=()=>new T.Texture();t.camera.position.set(0,4.65,6.65);t.camera.lookAt(0,1.3,-.35);t.baseQuaternion=t.camera.quaternion.clone();t.scene.add(t.camera);t.buildRoom();t.buildTable();t.batchBoxes(t.scene);t.buildHands();t.chipPiles=new T.Group();t.scene.add(t.chipPiles);t.resize();return t}
test('poker tavern preserves moving props and background rigs during batching',()=>{const t=scene();assert(t.dealerPlaque.children.some(o=>o.geometry?.type==='BoxGeometry'));assert(t.backgroundRigs.every(r=>r.head.children.length>0));assert.equal(t.torchFlames.length,24);assert(t.scene.children.some(o=>o.isInstancedMesh));});
test('specified hero cards remain real card meshes and pot/plaque follow game state',()=>{for(const count of [4,6,10]){const t=scene(count),players=Array.from({length:count},(_,i)=>({chips:2000,cards:i?[{r:2,s:'♣'},{r:3,s:'♥'}]:HERO_CARDS.hand,fold:false})),v={hand:HERO_CARDS.hand,board:HERO_CARDS.board,players,pot:240,bank:2000,dealer:0,done:false};t.sync(v,{animate:false});assert.equal(t.cardObjects.size,count*2+5);assert(t.potProp.visible);assert(t.dealerPlaque.visible);const first=t.dealerPlaque.position.clone();t.sync({...v,dealer:2},{animate:false});assert(first.distanceTo(t.dealerPlaque.position)>1);assert.equal(t.cardObjects.get('board0').sig,'13♦');t.sync({...v,done:true,showdown:true,winningSeats:[0]},{animate:false});assert(!t.potProp.visible);assert(!t.dealerPlaque.visible)}});

const screenRect=(obj,camera)=>{obj.updateWorldMatrix(true,true);camera.updateMatrixWorld(true);const pts=[];obj.traverse(m=>{const a=m.geometry?.attributes.position;if(!a)return;for(let i=0;i<a.count;i++)pts.push(new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(m.matrixWorld).project(camera))});return{l:Math.min(...pts.map(p=>p.x)),r:Math.max(...pts.map(p=>p.x)),b:Math.min(...pts.map(p=>p.y)),t:Math.max(...pts.map(p=>p.y))}};
const intersects=(a,b)=>a.l<b.r&&a.r>b.l&&a.b<b.t&&a.t>b.b;
test('pot and chips leave NPC cards and all community cards unobstructed',()=>{for(let count=4;count<=10;count++)for(const [width,height]of [[1920,1080],[1485,1023],[390,844]]){const t=scene(count);t.container.clientWidth=width;t.container.clientHeight=height;t.resize();const players=Array.from({length:count},()=>({chips:2000,cards:HERO_CARDS.hand,fold:false}));t.sync({hand:HERO_CARDS.hand,board:HERO_CARDS.board,players,pot:10000,bank:2000,done:false},{animate:false});const pot=screenRect(t.potProp,t.camera);for(const [id,card] of t.cardObjects)if(!id.startsWith('own'))assert(!intersects(pot,screenRect(card.obj,t.camera)),`pot covers ${id} at ${count} seats ${width}`);assert(t.chipPiles.children.length>0)}});
test('tavern architecture stops casting long shadows while blackjack keeps its fitted layout',()=>{const t=scene(6,BlackjackTable);assert(t instanceof PokerTavern);assert(!t.potProp);assert(!t.dealerPlaque);assert(!t.seatLines?.length);assert.equal(t.scene.children.filter(o=>o.userData.blackjackPlayingArea).length,1);t.roomArchitecture.traverse(o=>{if(o.isMesh)assert.equal(o.castShadow,false)});t.dealerSeat=6;t.arrangeSeats();const players=Array.from({length:6},()=>({bank:2000,hands:[{bet:100,cards:Array(6).fill(HERO_CARDS.hand[0])}]}));const dealer=Array(8).fill(HERO_CARDS.board[0]);t.showHands(players,dealer);assert.deepEqual(t.currentLayout,blackjackLayout(players,dealer));assert.equal(t.cardObjects.size,44);t.showBets(players);assert.equal(t.tableSurface.scale.z,1);assert.equal(t.deckAnchor.z,-2.85)});

test('all-in hands move into comparison positions before the board and stay there through payout',()=>{const t=scene(),players=Array.from({length:4},(_,i)=>({chips:0,cards:HERO_CARDS.hand,fold:i===1||i===3})),v={hand:HERO_CARDS.hand,players,board:[],runout:true,reveal:true,pot:200,bank:0,done:false};t.sync(v,{animate:false});const own=t.cardObjects.get('own0'),other=t.cardObjects.get('seat2-0');assert.equal(own.obj.parent,t.scene);assert.equal(other.sig,'13♣');assert(own.obj.position.x<0&&other.obj.position.x>0);assert(!t.cardObjects.get('seat1-0').obj.visible);assert(!own.obj.userData.winner);const pos=own.obj.position.clone();t.sync({...v,board:HERO_CARDS.board},{animate:false});assert(own.obj.position.equals(pos));const cards=[...t.cardObjects.values()].filter(c=>c.obj.visible);for(let i=0;i<cards.length;i++)for(let j=i+1;j<cards.length;j++){const a=new T.Box3().setFromObject(cards[i].obj),b=new T.Box3().setFromObject(cards[j].obj);assert(!(a.min.x<b.max.x&&a.max.x>b.min.x&&a.min.z<b.max.z&&a.max.z>b.min.z))}assert(screenRect(own.obj,t.camera).t<screenRect(t.cardObjects.get('board0').obj,t.camera).b);t.sync({...v,runout:false,board:HERO_CARDS.board,done:true,showdown:true},{animate:false});assert.equal(t.cardObjects.get('own0'),own);assert(own.obj.position.equals(pos));assert.equal(t.poseTweens.length,0)});
