import test from 'node:test';import assert from 'node:assert/strict';
import {Poker} from '../dist/poker.mjs';import {decide,PROFILES} from '../dist/strategy.mjs';import {observePoker,pokerAdaptation} from '../server/poker-adaptation.mjs';import {createRoom,command,tick,pack,unpack,snapshot} from '../server/rooms.mjs';
const rng=seed=>()=>{seed=Math.imul(seed,1664525)+1013904223|0;return(seed>>>0)/4294967296};
const read=(entered,folds,netBB)=>({entered,folds,faced:2,raises:0,actions:3,netBB});
function practice(rows){return{solo:true,seats:[{id:'human',auth:'human',bot:false},{id:'bot1',bot:true},{id:'bot2',bot:true},{id:'bot3',bot:true}],game:{players:Array.from({length:4},()=>({fold:false}))},pokerReads:{human:rows}}}
test('small entry increase measurably raises participation while keeping personality differences',()=>{const counts={old:0,new:0};for(let n=1;n<=140;n++){const g=new Poker([2000,2000,2000,2000],{rng:rng(n*7919+101)}),s=g.snapshot(g.turn);for(const profile of [0,1,3,7])for(const kind of ['old','new']){const d=decide(s,profile,{samples:12,rng:rng(n+900),participation:kind==='old'?0:.035});if(d.action!=='fold')counts[kind]++;if(d.action==='raise')assert(d.target>=s.legal.min&&d.target<=s.legal.max)}}console.log('Seeded entry comparison:',counts);assert(counts.new>counts.old);assert(counts.new-counts.old<counts.old*.3)});
test('practice exploits public overfolding and calling tendencies; win/loss pressure stays bounded',()=>{const tight=pokerAdaptation(practice(Array.from({length:12},()=>read(false,2,-12))),1),station=pokerAdaptation(practice(Array.from({length:12},()=>read(true,0,-12))),1),winning=pokerAdaptation(practice(Array.from({length:12},()=>read(true,0,12))),1);assert(tight.bluffBias>0&&tight.foldBias>0);assert(station.bluffBias<0&&station.valueBias>0);assert(winning.entryBias>station.entryBias);assert(station.valueBias>winning.valueBias);for(const a of [tight,station,winning])for(const n of Object.values(a))assert(Number.isFinite(n)&&Math.abs(n)<=.15);const multi=practice([read(true,0,15)]);multi.solo=false;assert.equal(pokerAdaptation(multi,1),null);assert.equal(pokerAdaptation(practice([]),1),null)});
test('learning never inspects private cards, counts posted blinds separately, and deduplicates rounds',()=>{const r=practice([]);Object.assign(r,{mode:'poker',round:1,statBasis:{human:{bank:2000}}});Object.assign(r.game,{done:true,count:4,dealer:0,bigBlind:20,smallBlind:10,paid:[0,0,0,0],actions:[{seat:3,street:0,kind:'raise',to:60},{seat:0,street:0,kind:'fold',to:0}],players:r.game.players.map(p=>({...p,chips:1990,total:10}))});Object.defineProperty(r.game,'deck',{get(){throw Error('deck leak')}});for(const p of r.game.players)Object.defineProperty(p,'cards',{get(){throw Error('hole card leak')}});observePoker(r);observePoker(r);assert.equal(r.pokerReads.human.length,1);assert.equal(r.pokerReads.human[0].entered,false);assert.equal(r.pokerReads.human[0].folds,1);pokerAdaptation(r,1);for(let n=2;n<=22;n++){r.round=n;observePoker(r)}assert.equal(r.pokerReads.human.length,12)});
test('practice reads survive persistence and continue without leaking through room snapshots',()=>{const r=createRoom('host',{mode:'poker',capacity:4,solo:true,name:'Host',role:0},0);r.solo=true;for(let n=0;n<3;n++)command(r,'host',{kind:'addBot'},0);command(r,'host',{kind:'start'},0);r.game.done=true;r.game.paid=[20,0,0,0];r.game.players[0].chips=2020;r.game.pending.clear();tick(r,2000);assert.equal(r.pokerReads[r.seats[0].id].length,1);assert(!JSON.stringify(snapshot(r,'host',2000)).includes('pokerReads'));const saved=unpack(pack(r));assert.deepEqual(saved.pokerReads,r.pokerReads);command(saved,'host',{kind:'next'},saved.reviewUntil+1);assert.equal(saved.round,2);assert.deepEqual(saved.pokerReads,r.pokerReads)});
test('adapted decisions stay legal over streets, all-ins and table sizes without mutating styles',()=>{const profiles=JSON.stringify(PROFILES);let count=0;for(const seats of [2,4,7])for(let n=0;n<3;n++){const random=rng(700+seats*10+n),g=new Poker(Array.from({length:seats},(_,i)=>i===1?45:1000),{rng:random,dealer:n%seats});while(!g.done){if(!g.pending.size){g.advance();continue}const s=g.snapshot(g.turn),d=decide(s,n,{samples:25,rng:random,adaptation:{entryBias:.04,bluffBias:.13,aggressionBias:.08,foldBias:.1,valueBias:.06,sizeBias:.05}});assert(Number.isFinite(d.equity));g.act(g.turn,d.action,d.target);assert(++count<1500)}}assert.equal(JSON.stringify(PROFILES),profiles);console.log('Legal adapted decisions:',count)});
