import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {createRoom,command,tick,snapshot,pack,unpack} from '../server/rooms.mjs';
import {RoomStore} from '../server/store.mjs';
import {guandanView,seatOrder} from '../dist/room-game.mjs';
const P=(name,role=0)=>({name,role});
const now=1700000000000;
function room(mode){const r=createRoom('host',{mode,capacity:4,...P('房主')},now);command(r,'friend',{kind:'join',...P('朋友',2)},now);command(r,'friend',{kind:'ready',ready:true},now);command(r,'host',{kind:'addBot',role:1},now);command(r,'host',{kind:'addBot',role:3},now);command(r,'host',{kind:'start'},now);return r}
test('all four games support invitations, explicit readiness, host bots and start',()=>{for(const mode of['poker','blackjack','craps','guandan']){const r=room(mode);assert.equal(r.status,'playing');assert.equal(r.seats[1].role,2);assert.equal(snapshot(r,'friend').you,1);assert.equal(snapshot(r,'stranger').game,undefined);assert.throws(()=>command(r,'friend',{kind:'addBot'},now));assert.throws(()=>command(r,'stranger',{kind:'act'},now));assert.throws(()=>command(r,'friend',{kind:'profile',...P('改名')},now));assert.equal(unpack(pack(r)).mode,mode)}});
test('poker private views never contain opponents cards or deck; stale and out-of-turn actions fail',()=>{const r=room('poker'),mine=snapshot(r,'host').game,friend=snapshot(r,'friend').game;assert(mine.players[0].cards.every(Boolean));assert.deepEqual(mine.players[1].cards,[null,null]);assert(friend.players[1].cards.every(Boolean));assert.deepEqual(friend.players[0].cards,[null,null]);assert(!('deck'in mine));assert.throws(()=>command(r,'host',{kind:'act',action:'fold',seq:-1},now));assert.throws(()=>command(r,'host',{kind:'act',action:'fold',seq:r.seq},now));});
test('guandan perspective rotates real identities, partner, target and private hands correctly',()=>{const r=room('guandan');for(let i=0;i<4;i++)r.seats[i].auth='user'+i;r.game.turn=0;r.game.act(0,[r.game.hands[0][0].id]);for(let i=0;i<4;i++){const s=snapshot(r,'user'+i),v=guandanView(s);assert.equal(v.g.hands[0].length,r.game.hands[i].length);assert.deepEqual(v.g.hands[0],r.game.hands[i]);assert(v.g.hands[1].every(c=>c===null));assert.equal(v.order[2],(i+2)%4);assert.equal(v.g.owner,(4-i)%4);assert.equal(s.seats[v.order[1]].role,r.seats[(i+1)%4].role);assert(!('deck'in s.game));assert(!('hands'in s.game))}});
test('blackjack staged deals hide the house hole card and resolve every seat',()=>{const r=room('blackjack');r.game.deck.sort((a,b)=>b.r-a.r);let time=now;command(r,'host',{kind:'act',action:'bet',amount:100,seq:r.seq},time);command(r,'friend',{kind:'act',action:'bet',amount:50,seq:r.seq},time);let sawHole=false;for(let n=0;n<90&&r.status==='playing';n++){time+=65000;tick(r,time);const s=snapshot(r,'friend',time);if(r.game.dealer.length===2&&!r.game.reveal){sawHole=true;assert.equal(s.game.dealer[1],null)}}assert(sawHole);assert.equal(r.status,'roundEnd');assert(r.game.players.every(p=>p.done));assert(r.game.players.every(p=>Number.isFinite(p.bank)));assert(!('deck'in snapshot(r,'host').game))});
test('craps shares dice while preserving independent wagers and rejects mid-roll bets',()=>{const r=room('craps');command(r,'host',{kind:'act',action:'bet',key:'field',amount:10,seq:r.seq},now);command(r,'friend',{kind:'act',action:'bet',key:'h6',amount:25,seq:r.seq},now);command(r,'host',{kind:'act',action:'roll',seq:r.seq},now+15000);assert.throws(()=>command(r,'friend',{kind:'act',action:'bet',key:'field',amount:10,seq:r.seq},now));const a=snapshot(r,'host'),b=snapshot(r,'friend');assert.deepEqual(a.game.roll,b.game.roll);assert.equal(a.game.table.bets.field,10);assert.equal(b.game.table.bets.field,0);r.game.roll.dice=[3,3];tick(r,now+19600);assert.equal(r.game.phase,'landed');tick(r,now+22600);assert.equal(r.game.tables[0].bank,1990);assert.equal(r.game.tables[1].bank,2200);assert.equal(r.game.tables[1].bets.h6,25);assert.equal(r.game.tables[0].history[0].total,6)});
test('serialized games finish with timed fallback and do not require a single host browser',()=>{for(const mode of['poker','guandan']){let r=room(mode),time=now,n=0;while(r.status==='playing'){assert(n++<700);time+=65000;r=unpack(pack(r));tick(r,time)}assert.equal(r.status,'roundEnd');assert(r.game.done)}});
test('disconnect leave transfers host and converts the correct seat to a computer',()=>{const r=room('poker'),original=r.seats[0].id;command(r,'host',{kind:'leave'},now);assert.equal(r.host,'friend');assert.equal(r.seats[0].id,original);assert(r.seats[0].bot);assert.equal(r.seats[0].role,0);assert.equal(snapshot(r,'friend').you,1)});
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../drizzle/0000_cheerful_longshot.sql',import.meta.url),'utf8'));return{prepare(sql){return{bind(...args){const stmt=sqlite.prepare(sql);return{async first(){return stmt.get(...args)},async run(){return{meta:{changes:stmt.run(...args).changes}}}}}}}}}
test('D1 compare-and-swap retains simultaneous joins and idempotent duplicate requests',async()=>{const store=new RoomStore(database()),r=await store.create('host',{mode:'poker',capacity:4,...P('房主')},now);const join=(auth,requestId)=>store.room(r.id,auth,{kind:'join',...P(auth),requestId},now);await Promise.all([join('one','1'.repeat(32)),join('two','2'.repeat(32))]);const s=await store.room(r.id,'host',null,now);assert.equal(s.seats.length,3);await join('one','1'.repeat(32));assert.equal((await store.room(r.id,'host',null,now)).seats.length,3)});

test('an active friend receives hosting after the host has been offline for a minute',async()=>{const store=new RoomStore(database()),r=await store.create('host',{mode:'poker',capacity:4,...P('Host')},now);await store.room(r.id,'friend',{kind:'join',...P('Friend'),requestId:'3'.repeat(32)},now);const moved=await store.room(r.id,'friend',null,now+61000);assert.equal(moved.host,true);assert.equal((await store.room(r.id,'host',null,now+61001)).host,false)});
