import test from 'node:test';
import assert from 'node:assert/strict';
import {createRoom,command,snapshot,pack,unpack,tick} from '../server/rooms.mjs';
import {skillAction,startSkills,settleSkills} from '../server/solo-skills.mjs';
import {newBlackjack,blackjackAct,blackjackTick,blackjackView} from '../dist/blackjack.mjs';
import {Craps} from '../dist/craps.mjs';
import {replayWagers} from '../dist/craps-wager-queue.mjs';
const card=r=>({r,s:'♠',id:'s'+r});
function room(mode,role=0){const r=createRoom('a',{mode,capacity:4,role,name:'A'},0);r.skill={enabled:true};for(let i=1;i<4;i++)command(r,'a',{kind:'addBot',role:i},0);command(r,'a',{kind:'start'},0);if(mode==='poker')r.game.turn=0;return r}
function bj(role){const r=room('blackjack',role),g=r.game;g.phase='players';g.turn=0;g.dealer=[card(10),card(7)];g.players.forEach(p=>{p.hands=[{cards:[card(10),card(6)],bet:100,done:false}];p.active=0;p.bet=100;p.bank=1900});return r}
test('poker random peek remains private, fee enters pot without changing call amounts',()=>{const r=room('poker'),before=r.game.pot,call=r.game.legal(0).call;skillAction(r,0,{},1);assert.equal(r.game.pot,before+100);assert.equal(r.game.legal(0).call,call);assert.equal(r.game.players[0].chips,1900);const mine=snapshot(r,'a',1);assert(mine.skill.peek.card);r.seats[1].auth='b';const other=snapshot(r,'b',1);assert.equal(other.skill.peek,null);assert.equal(other.skill.events.length,1);assert(!JSON.stringify(other.skill.events).includes('card'));assert.throws(()=>skillAction(r,0,{},2));assert.equal(unpack(pack(r)).skill.players[0].used,true)});
test('artisan costs 10 BB, swaps only requested card, and fees pay out once',()=>{const r=room('poker',1),g=r.game,old=g.players[0].cards[0],top=g.deck.at(-1);skillAction(r,0,{index:1},1);assert.equal(g.players[0].cards[0],old);assert.equal(g.players[0].cards[1],top);assert.equal(g.skillPot,200);for(let i=1;i<4;i++)g.players[i].fold=true;g.normalize();assert.equal(g.players.reduce((n,p)=>n+p.chips,0),8000);assert.equal(g.paid.reduce((n,p)=>n+p,0),g.pot)});
test('shield blocks raises and raise-like all-in; bounty pays per losing target',()=>{const r=room('poker',2),g=r.game;skillAction(r,0,{},1);assert.equal(g.legal(0).canRaise,false);assert.equal(g.legal(0).allIn,false);assert.throws(()=>g.act(0,'raise',100));for(let i=1;i<4;i++)g.players[i].fold=true;g.normalize();const before=g.players[0].chips;settleSkills(r);assert.equal(g.players[0].chips,before+g.pot*.1);settleSkills(r);assert.equal(g.players[0].chips,before+g.pot*.1);const b=room('poker',3);skillAction(b,0,{},1);assert.equal(new Set(b.skill.players[0].marks).size,2);b.game.paid=[0,0,0,0];b.game.done=true;settleSkills(b);assert.equal(b.skill.players[0].reward,200)});
test('blackjack peek does not reveal dealer; expires after draw; swap exchanges exact cards',()=>{const r=bj(0);skillAction(r,0,{},1);assert.equal(r.game.players[0].bank,1850);assert(snapshot(r,'a').skill.peek.card);assert.equal(snapshot(r,'a').game.dealer[1],null);r.game.deck.pop();assert.equal(snapshot(r,'a').skill.peek,null);const a=bj(1),mine=a.game.players[0].hands[0].cards[1],up=a.game.dealer[0];skillAction(a,0,{index:1},1);assert.equal(a.game.dealer[0],mine);assert.equal(a.game.players[0].hands[0].cards[1],up);assert.equal(a.game.players[0].bank,1850)});
test('overload is reflected in scores and uses 20 percent of active hand bet',()=>{const r=bj(2);skillAction(r,0,{choice:'self'},1);assert.equal(blackjackView(r.game).players[0].hands[0].points,18);assert.equal(r.game.players[0].bank,1880);const d=bj(2);skillAction(d,0,{choice:'dealer'},1);assert.equal(blackjackView(d.game).dealerPoints,9);d.game.reveal=true;assert.equal(blackjackView(d.game).dealerPoints,16)});
test('bounty net multipliers and reserve cover losses without negative balances',()=>{for(const [cards,dealer,net] of [[[10,10],[10,8],150],[[14,10],[10,8],250],[[10,6],[10,8],-150],[[10,10,5],[10,8],-200]]){const g=newBlackjack([1000],Math.random,0);g.players[0].bounty=true;blackjackAct(g,0,'bet',100,0);assert.equal(g.players[0].bank,800);g.players[0].hands[0].cards=cards.map(card);g.dealer=dealer.map(card);g.phase='dealer';g.nextAt=0;blackjackTick(g,[false],1);assert.equal(g.players[0].bank,1000+net);assert.equal(g.players[0].delta,net)}const g=newBlackjack([100],Math.random,0);g.players[0].bounty=true;assert.throws(()=>blackjackAct(g,0,'bet',100,0))});
test('craps optimistic replay and batch retain every click',()=>{const t=new Craps(2000),bets=Array.from({length:12},()=>({action:'bet',key:'field',amount:10})),draft=replayWagers(t,bets);assert.equal(t.bank,2000);assert.equal(draft.bank,1880);const r=room('craps');command(r,'a',{kind:'act',action:'betBatch',bets},1);assert.equal(r.game.tables[0].bets.field,120);assert.equal(r.game.tables[0].bank,1880)});
