import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../dist/vendor/three.module.min.js';
import {Guandan3D} from '../dist/guandan3d.mjs';
import {newBlackjack,blackjackAct,blackjackTick,blackjackView} from '../dist/blackjack.mjs';
import {blackjackLayout,RoomGame} from '../dist/room-game.mjs';
import {createRoom,command,tick,snapshot,pack,unpack} from '../server/rooms.mjs';
const now=1700000000000,C=r=>({r,s:'♠'});
function prepared(cards,bank=2000){const g=newBlackjack([bank],Math.random,now);blackjackAct(g,0,'bet',100,now);g.players[0].hands[0].cards=cards.map(C);g.dealer=[C(10),C(7)];g.phase='players';g.turn=0;return g}
function step(g,time){blackjackTick(g,[false],time);return g}
test('serialized duplicate Guandan plays retain their meshes and animation progress',()=>{const t=Object.assign(Object.create(Guandan3D.prototype),{scene:new T.Scene(),tweens:[],effects:[],elapsed:0,seatPoint:()=>new T.Vector3(),makeCard:()=>new T.Object3D(),tween(obj){this.tweens.push({obj})},disposeGroup(group){group.removeFromParent()}}),m={key:'pair:3',type:'pair',size:2,cards:[{id:1,...C(3)},{id:2,...C(3)}]};t.showPlays([null,m,null,null],1);const group=t.gdSeats.get(1).group,first=t.tweens[0];for(let n=0;n<10;n++)t.showPlays(JSON.parse(JSON.stringify([null,m,null,null])),1);assert.equal(t.gdSeats.get(1).group,group);assert.equal(t.tweens.length,2);assert.equal(t.tweens[0],first);t.showPlays([null,m,null,null],2);assert.notEqual(t.gdSeats.get(1).group,group)});
test('blackjack split deals sequentially, doubles the selected hand, and settles each hand',()=>{const g=prepared([8,8]);g.deck=[C(10),C(3),C(10)];blackjackAct(g,0,'split',null,now);assert.equal(g.players[0].bank,1800);assert.deepEqual(g.players[0].hands.map(h=>h.cards.length),[1,1]);assert.throws(()=>blackjackAct(g,0,'hit',null,now+500));step(g,now+1000);assert.deepEqual(g.players[0].hands.map(h=>h.cards.length),[2,1]);step(g,now+2100);step(g,now+3300);blackjackAct(g,0,'stand',null,now+3300);assert.equal(g.players[0].active,1);blackjackAct(g,0,'double',null,now+3301);step(g,now+4501);step(g,now+6301);assert(g.done);assert.deepEqual(g.players[0].hands.map(h=>h.delta),[100,200]);assert.equal(g.players[0].bank,2300)});
test('split aces get one card each and 21 is paid at 1:1, not blackjack 3:2',()=>{const g=prepared([14,14]);g.deck=[C(10),C(13)];blackjackAct(g,0,'split',null,now);step(g,now+1000);step(g,now+2100);step(g,now+3300);assert.equal(g.phase,'dealer');step(g,now+5100);assert.equal(g.players[0].bank,2200);assert(g.players[0].hands.every(h=>h.cards.length===2&&h.done))});
test('blackjack has no fixed table betting cap, rejects invalid stakes and hides hole-card points',()=>{const g=newBlackjack([1000000],Math.random,now);for(const n of[-1,0,1.5,1000001,Infinity])assert.throws(()=>blackjackAct(g,0,'bet',n,now));blackjackAct(g,0,'bet',150000,now);assert.equal(g.players[0].bank,850000);g.dealer=[C(6),C(14)];const v=blackjackView(g);assert.equal(v.dealerPoints,6);assert.equal(v.dealer[1],null);g.reveal=true;assert.equal(blackjackView(g).dealerPoints,17)});
function room(mode,capacity=2){const r=createRoom('host',{mode,capacity,name:'Host',role:0},now);command(r,'friend',{kind:'join',name:'Friend',role:1},now);command(r,'friend',{kind:'ready',ready:true},now);for(let n=2;n<capacity;n++)command(r,'host',{kind:'addBot',role:n%4},now);command(r,'host',{kind:'start'},now);return r}
test('two-player craps accepts immediate throws, unlimited betting and rotates only on seven-out',()=>{const r=room('craps');assert.equal(r.deadline,0);const immediate=unpack(pack(r));command(immediate,'host',{kind:'act',action:'roll'},now);assert.equal(immediate.game.phase,'rolling');assert.throws(()=>command(immediate,'friend',{kind:'act',action:'bet',key:'field',amount:10},now));command(r,'friend',{kind:'act',action:'bet',amount:25,key:'h6',seq:-1},now+500);assert.equal(snapshot(r,'host').game.others[1].bets.h6,25);let time=now+15000;tick(r,time);assert.equal(r.game.phase,'bets');tick(r,time+99999);assert.equal(r.game.phase,'bets');command(r,'friend',{kind:'act',action:'bet',amount:25,key:'h6'},time+99999);assert.equal(r.game.tables[1].bets.h6,50);assert.throws(()=>command(r,'friend',{kind:'act',action:'roll'},time+99999));
 const roll=dice=>{time+=100000;command(r,r.game.roller===0?'host':'friend',{kind:'act',action:'roll'},time);r.game.roll.dice=dice;time+=4600;tick(r,time);assert.equal(r.game.phase,'landed');time+=3000;tick(r,time);time+=2000;tick(r,time);time+=15000;tick(r,time)};
 roll([3,4]);assert.equal(r.game.roller,0,'come-out seven keeps shooter');roll([3,3]);assert.equal(r.game.point,6);roll([2,4]);assert.equal(r.game.roller,0,'making the point keeps shooter');roll([4,4]);assert.equal(r.game.point,8);roll([3,4]);assert.equal(r.game.roller,1,'seven-out changes shooter')});
test('every human independently continues after showdown, or leaves a bot to fill their seat',()=>{let r=room('poker',4),time=now;while(r.status==='playing'){time+=65000;r=unpack(pack(r));tick(r,time)}const round=r.round;assert(r.seats.filter(s=>!s.bot).every(s=>!s.ready));assert.throws(()=>command(r,'friend',{kind:'next'},r.endedAt));command(r,'friend',{kind:'next'},r.reviewUntil+1);assert.equal(r.round,round);command(r,'host',{kind:'leave'},r.reviewUntil+2);assert.equal(r.round,round+1);assert(r.seats[0].bot);assert.equal(snapshot(r,'friend').you,1)});
test('blackjack card layout retains every split card, with larger dealer cards',()=>{const p=Array.from({length:6},()=>({hands:Array.from({length:4},()=>({cards:Array.from({length:5},()=>C(3))}))})),d=[C(10),C(7)],layout=blackjackLayout(p,d);assert.equal(layout.length,122);assert.equal(new Set(layout.map(c=>c.key)).size,122);assert(layout.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.z)&&c.w>0));assert(layout[0].w>layout[2].w)});
test('blackjack limits resplitting to four hands and reserves every extra stake',()=>{const g=prepared([8,8]);g.deck=Array.from({length:10},()=>C(8));let t=now;for(let i=0;i<3;i++){blackjackAct(g,0,'split',null,t);step(g,t+1000);step(g,t+2100);step(g,t+3300);t+=3300}assert.equal(g.players[0].hands.length,4);assert.equal(g.players[0].bank,1600);assert.throws(()=>blackjackAct(g,0,'split',null,t));assert.equal(blackjackView(g).players[0].canSplit,false)});
test('full blackjack tables complete with conserved stakes and per-hand point totals',()=>{for(let n=1;n<=6;n++)for(let seed=1;seed<=5;seed++){let x=seed;const random=()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296},banks=Array(n).fill(2000),g=newBlackjack(banks,random,now);let time=now,steps=0;while(!g.done){assert(steps++<300);time+=2000;blackjackTick(g,Array(n).fill(true),time);const v=blackjackView(g);g.players.forEach((p,i)=>{assert(p.bank>=0);if(!g.done)assert.equal(p.bank+p.bet,2000);assert(v.players[i].hands.every(h=>Number.isInteger(h.points)));if(g.done)assert.equal(p.bank-2000,p.delta)})}}});
test('poker UI presents quick bets and lets the cards land before winner markers and continuation',()=>{const r=room('poker',4),nodes=new Map(),q=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',value:0});return nodes.get(s)},ui=Object.assign(Object.create(RoomGame.prototype),{q,order:[0,1,2,3],host:{querySelectorAll:()=>[]},rooms:{send:async()=>{}},now:()=>now});let view;ui.scene={sync:v=>view=v};ui.renderTable(snapshot(r,'host',now));assert.match(q('.mp-controls').innerHTML,/data-size="0.33"/);assert.match(q('.mp-controls').innerHTML,/data-range/);assert.match(q('.mp-phase').innerHTML,/底池 POT/);assert.match(q('.mp-labels').innerHTML,/data-at-head="true"/);r.game.board=r.game.deck.splice(0,5);r.game.finish();r.status='roundEnd';r.seats.forEach(s=>s.ready=s.bot);r.endedAt=now;r.reviewUntil=now+6000;const s=snapshot(r,'host',now);ui.renderTable(s);assert.equal(view.winningCards.length,0);assert.equal(q('.mp-result').innerHTML,'');ui.now=()=>now+2500;ui.renderTable(s);assert(view.winningCards.length>=5);assert.equal(q('.mp-result').innerHTML,'');ui.now=()=>now+6100;ui.renderTable(s);assert.match(q('.mp-result').innerHTML,/继续下一局/);assert.doesNotMatch(q('.mp-result').innerHTML,/返回准备区/)});
