const encoder=new TextEncoder(),WINDOW=15*60*1000,COOKIE='__Host-bb_access';
const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
const unhex=s=>Uint8Array.from(s.match(/../g)??[],v=>parseInt(v,16));
const encode=s=>btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const decode=s=>atob(s.replaceAll('-','+').replaceAll('_','/'));
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cookie=(value,age)=>`${COOKIE}=${value}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`;
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'};
async function signingKey(env){return crypto.subtle.importKey('raw',unhex(env.ACCESS_SESSION_KEY),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
export async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:unhex(salt),iterations:100000,hash:'SHA-256'},key,256))}
async function authenticated(req,env){try{const token=req.headers.get('cookie')?.split(';').map(c=>c.trim()).find(c=>c.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token||token.length>600)return false;const parts=token.split('.');if(parts.length!==2)return false;const [payload,sig]=parts,body=JSON.parse(decode(payload));if(!Number.isSafeInteger(body.exp)||body.exp<=Date.now()||body.exp>Date.now()+31*86400000||typeof body.id!=='string')return false;return await crypto.subtle.verify('HMAC',await signingKey(env),Uint8Array.from(decode(sig),c=>c.charCodeAt(0)),encoder.encode(payload))}catch{return false}}
const destination=v=>typeof v==='string'&&v.startsWith('/')&&!v.startsWith('//')&&!/[\\\r\n]/.test(v)&&!v.startsWith('/access')?v:'/';
function gate(returnTo='/',error='',status=200){return new Response(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>进入积木牌局</title><style>*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;background:radial-gradient(ellipse at top,#3d492d,#101d17 65%);color:#f0ecd7;font-family:system-ui,sans-serif;padding:24px}main{width:min(100%,420px);padding:34px;background:#152a20;border:1px solid #9a8956;border-radius:16px;box-shadow:0 20px 80px #0007}.brand{font-family:Georgia,serif;color:#ddca89;letter-spacing:2px;font-weight:bold}h1{font-size:28px;margin:26px 0 12px}p{color:#bcc4ad;line-height:1.7}label{display:block;margin-top:22px;font-size:16px}input[type=password]{width:100%;background:#0f2018;border:1px solid #7c885b;border-radius:8px;padding:15px;color:#fff;font-size:22px;margin-top:9px;letter-spacing:3px}input:focus{outline:2px solid #d8e995;outline-offset:2px}.remember{display:flex;gap:9px;align-items:center;color:#c2cbb4;font-size:14px}.remember input{width:18px;height:18px;accent-color:#d6e993}button{margin-top:24px;width:100%;padding:15px;border:0;border-radius:8px;background:#d5e997;color:#193022;font-size:18px;font-weight:bold;cursor:pointer}.error{color:#ffc4a7;min-height:24px;margin-bottom:0;font-size:15px}</style></head><body><main><div class="brand">BRICK &amp; BLUFF</div><h1>朋友，欢迎入座</h1><p>输入访问密码，进入游戏大厅。<br>无需邮箱或注册账号。</p><form method="post" action="/access/login"><input type="hidden" name="returnTo" value="${escape(destination(returnTo))}"><label for="password">进入密码</label><input id="password" name="password" type="password" inputmode="numeric" autocomplete="current-password" maxlength="128" required><label class="remember"><input type="checkbox" name="remember" value="yes" checked>在此设备上记住 30 天</label><p class="error" role="alert">${escape(error)}</p><button type="submit">进入大厅 →</button></form></main></body></html>`,{status,headers:{...headers,'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"}})}

// All routes and API calls pass this gate, including direct asset URLs.
export async function accessGate(req,env){const url=new URL(req.url);if(!/^[a-f0-9]{32}:[a-f0-9]{64}$/.test(env.ACCESS_PASSWORD_HASH??'')||!/^[a-f0-9]{64}$/.test(env.ACCESS_SESSION_KEY??''))return new Response('访问入口正在配置，请稍后刷新。',{status:503,headers});
 if(url.pathname==='/access/logout'){if(req.method!=='POST'||req.headers.get('origin')!==url.origin)return new Response('Forbidden',{status:403,headers});return new Response(null,{status:303,headers:{...headers,Location:'/', 'Set-Cookie':cookie('',0)}})}
 if(url.pathname==='/access/login'){if(req.method!=='POST')return gate();if(req.headers.get('origin')!==url.origin)return new Response('Forbidden',{status:403,headers});if(!req.headers.get('content-type')?.startsWith('application/x-www-form-urlencoded'))return new Response('Unsupported format',{status:415,headers});const raw=await req.text();if(raw.length>2048)return new Response('Request too large',{status:413,headers});const form=new URLSearchParams(raw),returnTo=destination(form.get('returnTo')),password=form.get('password')??'';if(!env.DB)return gate(returnTo,'入口暂不可用，请稍后重试。',503);
  try{const now=Date.now(),ip=req.headers.get('cf-connecting-ip')??'unknown',key=hex(await crypto.subtle.sign('HMAC',await signingKey(env),encoder.encode(ip)));
   const attempt=await env.DB.prepare('INSERT INTO access_attempts (id, attempts, started) VALUES (?, 1, ?) ON CONFLICT(id) DO UPDATE SET attempts = CASE WHEN started <= ? THEN 1 ELSE attempts + 1 END, started = CASE WHEN started <= ? THEN excluded.started ELSE started END RETURNING attempts').bind(key,now,now-WINDOW,now-WINDOW).first();
   if(!attempt||attempt.attempts>8)return gate(returnTo,'尝试次数较多，请 15 分钟后再试。',429);
   const [salt,expected]=env.ACCESS_PASSWORD_HASH.split(':'),actual=await passwordHash(password,salt);let diff=0;for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);if(diff)return gate(returnTo,'密码不正确，请重新输入。',401);
   await env.DB.prepare('DELETE FROM access_attempts WHERE id = ? OR started < ?').bind(key,now-WINDOW).run();const age=form.get('remember')==='yes'?30*86400:86400,payload=encode(JSON.stringify({exp:now+age*1000,id:crypto.randomUUID()})),sig=await crypto.subtle.sign('HMAC',await signingKey(env),encoder.encode(payload));return new Response(null,{status:303,headers:{...headers,Location:returnTo,'Set-Cookie':cookie(payload+'.'+encode(String.fromCharCode(...new Uint8Array(sig))),age)}})
  }catch{return gate(returnTo,'入口暂不可用，请稍后重试。',503)}
 }
 if(await authenticated(req,env))return null;
 if(url.pathname==='/'||url.pathname==='/index.html')return gate(url.pathname+url.search);
 return new Response(JSON.stringify({error:'请先输入访问密码',code:'ACCESS_REQUIRED'}),{status:401,headers:{...headers,'Content-Type':'application/json; charset=utf-8'}});
}
