import {entryChips} from '../dist/poker-stakes.mjs';
import {chipBalance} from './chip-balances.mjs';
import {createRoom,pack,unpack,command,tick,snapshot,seatOf} from './rooms.mjs';
export const ROOM_IDLE_MS=20*60*1000;
const uuid=()=>crypto.randomUUID().replaceAll('-','');
const check=(v,m)=>{if(!v)throw Error(m)};
export class Club {
 constructor(db){this.db=db}
 tableTotal(s,p){let total=0;for(const raw of Object.values(s.rooms)){const r=JSON.parse(raw);const i=r.seats.findIndex(x=>x.cashOwner===p.auth||(r.id===p.room&&x.auth===p.auth));if(i>=0)total+=chipBalance(r,i).totalChips}return total}

 async change(fn){for(let n=0;n<12;n++){let row=await this.db.prepare('SELECT version,state FROM club_state WHERE id = 1').bind().first();if(!row){await this.db.prepare('INSERT OR IGNORE INTO club_state (id,version,state) VALUES (1,0,?)').bind('{"players":[],"rooms":{},"audit":[]}').run();continue}const state=JSON.parse(row.state);const result=await fn(state);const encoded=JSON.stringify(state);if(encoded===row.state)return result;check(new TextEncoder().encode(encoded).length<1800000,'大厅数据已满，请联系管理员');const saved=await this.db.prepare('UPDATE club_state SET state = ?, version = version + 1 WHERE id = 1 AND version = ?').bind(encoded,row.version).run();if(saved.meta.changes)return result}throw Error('大厅正在同步，请重试')}
 ensure(s,auth,agent,now){let p=s.players.find(p=>p.auth===auth);if(!p){check(s.players.length<1000,'设备名额已满');p={id:uuid(),auth,name:'',role:0,bank:s.deletedDevices?.includes(auth)?0:2000,status:'pending',seen:now,created:now,agent:String(agent||'未知浏览器').slice(0,180),room:null};s.players.push(p)}if(now-p.seen>=10000)p.seen=now;return p}
 view(s,p,now){const r=p.room&&s.rooms[p.room]?unpack(s.rooms[p.room]):null,i=r?r.seats.findIndex(x=>x.auth===p.auth||x.cashOwner===p.auth):-1;let table=0;if(i>=0){table=r.mode==='poker'&&r.game&&!r.game.done?(r.game.players[i]?.chips??r.seats[i].bank):r.seats[i].bank}const pending=Object.values(s.rooms).map(raw=>JSON.parse(raw)).flatMap(room=>room.seats.filter(seat=>seat.cashOwner===p.auth&&room.id!==p.room));table+=pending.reduce((n,seat)=>n+seat.bank,0);return{id:p.id,name:p.name,role:p.role,status:p.status,bank:p.bank,tableBank:table,activeRoom:p.room,settling:pending.length>0||!!r?.seats[i]?.cashOwner,online:now-p.seen<45000,seen:p.seen,created:p.created,agent:p.agent}}
 release(s,r,seat,amount){const p=s.players.find(p=>p.auth===(seat.cashOwner||seat.auth));if(p&&(p.room===r.id||seat.cashOwner)){p.bank=Math.round(p.bank+Math.max(0,amount));if(p.room===r.id)p.room=null}delete seat.cashOwner}
 closeRoom(s,r){for(let i=0;i<r.seats.length;i++)this.release(s,r,r.seats[i],r.mode==='guandan'?0:chipBalance(r,i).totalChips);for(const p of s.players)if(p.room===r.id)p.room=null;delete s.rooms[r.id]}
 advance(s,now,only=null){for(const [id,raw] of Object.entries(s.rooms)){const meta=JSON.parse(raw);if(!meta.closeAfterRound&&id!==only&&only!==true&&now-(meta.lastHumanAction??now)<ROOM_IDLE_MS&&(meta.expires>now||meta.status==='playing')&&meta.seats.some(x=>x.auth||x.cashOwner))continue;const r=unpack(raw);r.lastHumanAction??=now;if(r.closeAfterRound&&r.status==='playing'&&r.seats.every(x=>x.bot)){for(let n=0;n<128&&r.status==='playing'&&r.nextAt<=now;n++)tick(r,r.nextAt)}if(r.closeAfterRound&&r.status==='roundEnd'){this.closeRoom(s,r);continue}if(now-r.lastHumanAction>=ROOM_IDLE_MS){this.closeRoom(s,r);continue}tick(r,now);if(r.closeAfterRound&&r.status==='roundEnd'){this.closeRoom(s,r);continue}if(r.mode==='craps'&&r.status==='playing'&&['bets','ready','result'].includes(r.game.phase)){r.seats.forEach((seat,i)=>{if(seat.cashOwner){const t=r.game.tables[i];t.clear();seat.bank=t.bank;if(!t.escrow){this.release(s,r,seat,t.bank);t.bank=0;seat.bank=0}}})}if(r.status==='roundEnd')for(const seat of r.seats)if(seat.cashOwner)this.release(s,r,seat,seat.bank);if((r.expires<=now&&r.status!=='playing')||!r.seats.some(x=>x.auth||x.cashOwner)){for(let i=0;i<r.seats.length;i++){const seat=r.seats[i];this.release(s,r,seat,r.mode==='poker'&&r.game&&!r.game.done?(r.game.players[i]?.chips??seat.bank):seat.bank)}delete s.rooms[id]}else s.rooms[id]=pack(r)}}
 async session(auth,agent,now){return this.change(s=>{const p=this.ensure(s,auth,agent,now);this.advance(s,now,p.room);return{player:this.view(s,p,now),players:(p.name&&p.status==='allowed'?s.players:[]).filter(p=>p.name&&p.status==='allowed'&&now-p.seen<45000).map(p=>({id:p.id,name:p.name,role:p.role,totalChips:p.bank+this.tableTotal(s,p),online:now-p.seen<45000})),admin:false}})}
 async profile(auth,data,now){return this.change(s=>{const p=s.players.find(p=>p.auth===auth);check(p,'请刷新页面');check(!p.room,'请先离开牌桌');const name=String(data.name??'').trim();check(name.length>=1&&name.length<=16,'昵称需要 1–16 个字符');const role=data.role??p.role;check(Number.isInteger(role)&&role>=0&&role<4,'请选择角色');check(!s.players.some(q=>q.id!==p.id&&q.name===name),'昵称已被使用');p.name=name;p.role=role;p.seen=now;return{player:this.view(s,p,now)}})}
 allowed(s,auth){const p=s.players.find(p=>p.auth===auth);check(p?.name,'请先填写昵称');check(p.status==='allowed',p.status==='blocked'?'此设备已被管理员停用':'等待管理员允许此设备进入');return p}
 async admin(auth,data,now){return this.change(s=>{this.advance(s,now);const actor=s.players.find(p=>p.auth===auth);check(actor,'请刷新页面');if(data){check(/^[a-f0-9]{32}$/.test(data.requestId??''),'请求标识无效');if(!s.audit.some(x=>x.requestId===data.requestId)){
 let target=data.id,name='',amount=0,status='';
 if(data.kind==='closeRoom'){check(s.rooms[data.id],'牌局已关闭');const r=unpack(s.rooms[data.id]);name=r.mode;this.closeRoom(s,r)}
 else{const p=s.players.find(p=>p.id===data.id);check(p,'找不到设备');name=p.name;status=p.status;
 if(data.kind==='deletePlayer'){check(p.id!==actor.id,'不能删除当前管理员设备');if(p.room&&s.rooms[p.room])this.closeRoom(s,unpack(s.rooms[p.room]));s.deletedDevices??=[];if(!s.deletedDevices.includes(p.auth))s.deletedDevices.push(p.auth);s.players=s.players.filter(x=>x.id!==p.id)}
 else if(data.kind==='grant'){check(Number.isSafeInteger(data.amount)&&data.amount>0&&data.amount<=10000000,'请输入 1–10000000 的整数');check(p.bank+data.amount<=1000000000,'余额超过上限');p.bank+=data.amount;amount=data.amount}
 else{check(data.kind==='permission'&&['allowed','blocked'].includes(data.status),'未知管理操作');check(p.id!==actor.id||data.status==='allowed','不能停用当前管理员设备');p.status=data.status;status=p.status}}
 s.audit.unshift({requestId:data.requestId,actor:actor.id,target,name,kind:data.kind,amount,status,at:now});s.audit=s.audit.slice(0,1000)}}return{actorId:actor.id,players:s.players.map(p=>this.view(s,p,now)),rooms:Object.values(s.rooms).map(unpack).map(r=>({id:r.id,mode:r.mode,status:r.status,count:r.seats.length,humans:r.seats.filter(x=>x.auth).length,lastHumanAction:r.lastHumanAction,idleMinutes:Math.floor((now-r.lastHumanAction)/60000)})),audit:s.audit.slice(0,60)}})}
 async list(auth,now){return this.change(s=>{this.advance(s,now);this.allowed(s,auth);return{rooms:Object.values(s.rooms).map(unpack).filter(r=>!r.solo||seatOf(r,auth)>=0).map(r=>({id:r.id,mode:r.mode,smallBlind:r.smallBlind??10,entryChips:r.mode==='poker'?entryChips(r.smallBlind):0,name:r.seats.find(x=>x.auth===r.host)?.name??'朋友',capacity:r.capacity,count:r.seats.length,status:r.status,member:seatOf(r,auth)>=0,joinable:seatOf(r,auth)>=0||r.seats.length<r.capacity}))}})}
 async create(auth,data,now){return this.change(s=>{this.advance(s,now);const p=this.allowed(s,auth);check(!p.room,'请先离开当前牌桌');check(Object.keys(s.rooms).length<40,'当前牌桌较多，请稍后再试');const solo=data.solo===true;const capacity=solo&&['craps','roulette','blackjack'].includes(data.mode)?1:data.capacity;const r=createRoom(auth,{...data,name:p.name,role:p.role,capacity,solo},now);r.solo=solo;r.lastHumanAction=now;r.skill={enabled:['poker','blackjack'].includes(r.mode)&&data.skills===true,role:p.role};this.fund(p,r,r.seats[0]);if(solo){while(r.seats.length<r.capacity)command(r,auth,{kind:'addBot'},now);command(r,auth,{kind:'start'},now)}s.rooms[r.id]=pack(r);return snapshot(r,auth,now)})}
 fund(p,r,seat){check(r.mode!=='poker'||p.bank>=entryChips(r.smallBlind),'该德州牌桌需至少 '+entryChips(r.smallBlind)+' 筹码（100 大盲）才能进入');check(r.mode==='guandan'||p.bank>0,'筹码不足，请联系管理员发放');seat.bank=r.mode==='guandan'?0:Math.round(p.bank);if(r.mode!=='guandan')p.bank=0;p.room=r.id}
 async room(id,auth,data,now,since=null){return this.change(s=>{this.advance(s,now,id);const p=this.allowed(s,auth);if(!s.rooms[id])return{closed:true,message:'牌局已关闭，筹码已退回玩家中心'};const r=unpack(s.rooms[id]);check(!r.solo||seatOf(r,auth)>=0,'这是单人牌桌');let i=seatOf(r,auth);if(i>=0){if(now-r.seats[i].seen>=10000)r.seats[i].seen=now;const host=r.seats.find(x=>x.auth===r.host);if(!host||now-host.seen>60000){r.host=auth;r.seq++}}if(data){check(/^[a-f0-9]{32}$/.test(data.requestId??''),'请求标识无效');const key=auth+':'+data.requestId;if(!r.requests.includes(key)){if(data.kind==='join'&&i<0){check(!p.room,'请先离开当前牌桌');command(r,auth,{...data,name:p.name,role:p.role},now);i=seatOf(r,auth);this.fund(p,r,r.seats[i])}else if(data.kind==='leave'){
 check(i>=0,'你尚未入座');const seat=r.seats[i];const available=r.status!=='playing'||seat.waiting?seat.bank:r.mode==='poker'?r.game.players[i].chips:r.mode==='craps'?r.game.tables[i].bank:['blackjack','roulette'].includes(r.mode)?r.game.players[i].bank:0;
 // 大老二本副尚未结算：筹码先留在桌面，等本副结算完再退回，避免中途离桌逃掉结算。
 const deferSettle=r.mode==='bigtwo'&&r.status==='playing'&&!seat.waiting;
 this.release(s,r,seat,deferSettle?0:available);if(deferSettle){seat.cashOwner=seat.auth;r.closeAfterRound=true;}if(r.status==='playing'&&!seat.waiting){if(r.mode==='poker')r.game.players[i].chips=0;else if(r.mode==='craps')r.game.tables[i].bank=0;else if(['blackjack','roulette'].includes(r.mode))r.game.players[i].bank=0;if(r.mode==='blackjack'){const bp=r.game.players[i];bp.departed=true;bp.hands.forEach(h=>h.done=true);bp.done=true}if(!deferSettle)seat.bank=0}command(r,auth,data,now);
 }else{if(data.kind==='profile')throw Error('请返回大厅修改个人形象');if(['next','start'].includes(data.kind)&&i>=0&&p.bank){r.seats[i].bank+=p.bank;p.bank=0}command(r,auth,data,now)}r.lastHumanAction=now;r.requests.push(key);r.requests=r.requests.slice(-160)}}tick(r,now);if(r.closeAfterRound&&r.status==='roundEnd'){this.closeRoom(s,r);return{closed:true,message:'托管牌局已结算，筹码已退回，房间已关闭'}}if(r.status==='roundEnd')for(const seat of r.seats)if(seat.cashOwner)this.release(s,r,seat,seat.bank);s.rooms[id]=pack(r);const revision=String(r.seq)+':'+r.seats.map(seat=>seat.bot||now-seat.seen<25000?1:0).join('');if(!data&&since===revision)return{unchanged:true,serverNow:now};return{...snapshot(r,auth,now),revision}})}
}
